---
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: hana-vnet
        address_prefixes: "10.0.0.0/16" 
    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: hana-subnet
        address_prefix: "10.0.1.0/24"
        virtual_network: hana-vnet
      register: hana_cluster_subnet
    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
         resource_group: "{{ resource_group }}"
         name: "{{ resource_group }}-hana-nsg"
         rules:
           - name: SSH
             protocol: Tcp
             destination_port_range: 22
             access: Allow
             priority: 1001
             direction: Inbound
             source_address_prefix: "{{ allowed_source_ip_prefix }}"

    - name: Create vms
      with_sequence: start=1 end="{{ vm_count }}"
      include_role:
        name: create-azure-vm
      vars:
        az_resource_group: "{{ resource_group }}"
        public_ip_allocation_type: Static
        pip_name: "{{ vm_group }}-pip{{ item }}"
        pip_sku: Standard
        domain_name: "{{ az_domain_name }}-{{ vm_group }}{{ item }}"
        nic_name: "{{ vm_group }}-nic{{ item }}"
        subnet_name: "hana-subnet"
        vnet_name: "hana-vnet"
        enable_accelerated_networking: True
        vm_group: "{{ vm_group }}"
        vm_size: Standard_D8s_v3
        machine_name: "{{ vm_group }}-{{ item }}"
        managed_disk_type: Standard_LRS
        vm_user: "{{ vm_user }}"
        nsg_name: "{{ resource_group }}-hana-nsg"
