---

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |      Set Runtime Paramters - e.g Sub ID , Resource group name              |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

# ----------------------------------------
# BEGIN
# ----------------------------------------

- name: " Retrieve Subscription ID and Resource Group Name"
  shell: curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq
  register: hanavmmetadata
  no_log: false
  changed_when: false

- name: save the Json data to a Variable as a Fact
  set_fact:
    jsondata: "{{ hanavmmetadata.stdout | from_json }}"
  no_log: true

- name: " Extract Subscription ID "
  set_fact:
    sap_hana_fencing_spn_subscription_id: "{{ jsondata | json_query('compute.subscriptionId') }}"
  no_log: true
    
- name: " Extract ResourceGroup Name "
  set_fact:
    resource_group_name: "{{ jsondata | json_query('compute.resourceGroupName') }}"
  no_log: true
   
- name: set the primary intance db nic and admin nic IP
  set_fact:
    primary_instance_ip_db: "{{ hostvars[primary_instance_name]['ansible_eth0']['ipv4']['address'] }}"
    primary_instance_ip_admin: "{{ hostvars[primary_instance_name]['ansible_eth1']['ipv4']['address'] }}"

- name: set the secondary intance db nic and admin nic IP
  set_fact:
    secondary_instance_ip_db: "{{ hostvars[secondary_instance_name]['ansible_eth0']['ipv4']['address'] }}"
    secondary_instance_ip_admin: "{{ hostvars[secondary_instance_name]['ansible_eth1']['ipv4']['address'] }}"

- name: "Show Subscription ID"
  debug:
    var: sap_hana_fencing_spn_subscription_id
    verbosity: 2

- name: "Show Resource Group Name"
  debug:
    var: resource_group_name
    verbosity: 2

- name: Ensure HANA DB version is checked and captured
  when: ansible_hostname == primary_instance_name
  block:

    - name: Check HANA DB Version and register
      become_user: "{{ hdb_sid | lower }}adm"
      shell: /hana/shared/HDB/HDB00/HDB version
      register: hdbversion
      changed_when: false
    - debug:
        var: hdbversion.stdout_lines

    - name: capture the Hana DB version
      set_fact:
        hdb_version: "{{ hdbversion.stdout_lines.1.split().1 }}"
    - debug:
        var: hdb_version
    - debug:
        var: hdb_version[0:2]


# /*---------------------------------------------------------------------------8
# |                                   END                                     |
# +------------------------------------4--------------------------------------*/

...
