---

# Variables in this file are required by the role, but are computed from default variables (e.g. sid),
# from the playbook/environment (e.g. hana_database), or are "SAP standard" values.
#
# They may be overridden, if required, but normally are not


db_sid_admin_user: "{{ db_sid | lower }}adm"

...
