---
# RHEL-3.10 Disable Transparent Hugepages (THP)
# RHEL-3.12 Configure Processor C-States (not relevant for IBM Power LE (ppc64le))
# SAP Note 2205917 - SAP HANA DB Recommended OS settings for SLES 12 / SLES for SAP Applications 12
# TODO: when tier = HANA; put in a block; move to sap specific
- name:     Task Disable Transparent Hugepages & Configure Processor C-States 1
  ansible.builtin.command:    "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
  changed_when: false

- name:     Task Disable Transparent Hugepages & Configure Processor C-States 2
  ansible.builtin.lineinfile:
     dest:    /etc/default/grub
     regexp:  "GRUB_CMDLINE_LINUX="
     line:    "GRUB_CMDLINE_LINUX='crashkernel=auto  @ vconsole.keymap=us @kernel_arguments: transparent_hugepage=never intel_idle.max_cstate=1 processor.max_cstate=1'"

- name:     Task Disable Transparent Hugepages & Configure Processor C-States 3
  ansible.builtin.command:    grub2-mkconfig -o /boot/grub2/grub.cfg
  changed_when: false

- name:                                Enable OS profile for SAP-HANA
  ansible.builtin.command:             "{{ item.osCommand }}"
  changed_when:                        false
  register:                            saphanaprofile
  loop:
    - { osFamily: "REDHAT", osCommand: "tuned-adm profile sap-hana" }
    - { osFamily: "SUSE"  , osCommand: "saptune solution apply HANA"}
  when:
    - node_tier == "hana"
    - distro_family == item.osFamily

- name:                                "tuned HANA profile results"
  ansible.builtin.debug:
    var:                               saphanaprofile

- name:                                Enable OS profile for SAP-Netweaver
  ansible.builtin.command:             "{{ item.osCommand }}"
  changed_when:                        false
  register:                            saphanaprofile
  loop:
    - { osFamily: "REDHAT", osCommand: "tuned-adm profile sap-netweaver" }
    - { osFamily: "SUSE"  , osCommand: "saptune solution apply netweaver"}
  when:
    - node_tier == "scs"
    - distro_family == item.osFamily
    - bom_base_name.startswith('S4')

- name:                                "tuned HANA profile results"
  ansible.builtin.debug:
    var:                               saphanaprofile
...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +------------------------------------4--------------------------------------*/
