# Tasks:
#   OS: hosts file, Entries - /etc/hosts
#
# TODO:

---
#   OS: hosts file, Entries - /etc/hosts
- name:           "OS: Common, Entries - /etc/hosts"
  blockinfile:
    path:         /etc/hosts
    mode:         0644
    create:       yes
    backup:       yes
    state:        present
    block:        "{{ lookup('file', 'hosts.block') }}"
    marker:       "# {mark} ANSIBLE MANAGED BLOCK - COMMON"
    marker_begin: "\n# BEGIN"
    marker_end:   "# END"

# - name:           "OS: Insert empty line before the marker"
#   lineinfile:
#     path:         /etc/hosts
#     insertbefore: '^# BEGIN ANSIBLE MANAGED BLOCK.*$'
#     line:         ''

- name:           "OS: SID, Entries - /etc/hosts"
  blockinfile:
    path:         /etc/hosts
    mode:         0644
    create:       yes
    state:        present
    block:        "{{ lookup('template', 'hosts.j2') }}"
    marker:       "# {mark} ANSIBLE MANAGED BLOCK - {{ sap_sid|upper }}"
