# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                   Playbook for SAP Web Dispatcher Install                   |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

# TODO: Playbook not yet written

- hosts:          "{{ sap_sid|upper }}_WEB"

  name:           SAP Installation - WEB
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:

  # - name: Test Connection                                     # Simple connection test for troubleshooting
  #   ping:
  - include_role:
      name:     roles-sap-os/sap-mounts



...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +------------------------------------4--------------------------------------*/
