# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                      Prepare for HANA DB Install                           |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

- hosts:                               localhost
  name:                                Get SAP Password from KeyVault
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults

  tasks:
    - name:                            Set hdb fact
      ansible.builtin.set_fact:
        tier:                          hdb

    - name:                            Include 0.1-passwords Role
      ansible.builtin.include_role:
        name:                          roles-misc/0.1-passwords
        public:                        true
      tags:
        - 0.1-passwords

    - name:                            Remove .step4 flag
      ansible.builtin.file:
        path:                          "{{ _workspace_directory }}/.step4"
        state:                          absent

# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                      Playbook for HANA DB Install                           |
# |                                                                            |
# +------------------------------------4--------------------------------------*/


- hosts:                               "{{ sap_sid|upper }}_DB"

  name:                                DB Installation - HANA
  remote_user:                         "{{ orchestration_ansible_user }}"
  become:                              true
  become_user:                         root
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here.
#
# -------------------------------------+---------------------------------------8

    - name:                            Setting the DB facts
      ansible.builtin.set_fact:
        tier:                          hdb                                     # Actions for HANA DB Serve
        main_password:                 "{{ hostvars.localhost.sap_password }}"
      tags:
        - always

    - name:                            Show SAP password
      ansible.builtin.debug:
        msg:                           "{{ hostvars.localhost.sap_password }}"
        verbosity:                     2

    - block:
        - name:                        4.0.0 hana db install
          ansible.builtin.include_role:
            name:                      redhat_sap.sap_hana_deployment
          vars:
            sap_hana_installdir: "/usr/sap/install/CD_HDBSERVER/SAP_HANA_DATABASE"
            # Passwords:
            sap_hana_deployment_sapadm_password: "{{ main_password }}"
            sap_hana_deployment_common_master_password: "{{ main_password }}"
            sap_hana_deployment_sidadm_password: "{{ main_password }}"
            sap_hana_deployment_hana_db_system_password: "{{ main_password }}"

            # FIXME: Missing components and component_root configuration.

            # Configurations:
            sap_hana_deployment_hana_install_path: "/hana/shared"  # Default
            sap_hana_deployment_hana_sid: "{{ db_sid|upper }}"
            sap_hana_deployment_hana_instance_number: "{{ hdb_instance_number }}"
            sap_hana_deployment_hana_env_type: "custom"

      tags:
        - 4.0.0-hdb-install

# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                         PLAYBOOK FOR HANA DB LOGGING                       |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- hosts:                               localhost
  name:                                Log results
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults

  tasks:
    - name:                           Create .step4 flag
      ansible.builtin.file:
        path:                         "{{ _workspace_directory }}/.step4"
        state:                        touch
        mode:                         0755


...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +------------------------------------4--------------------------------------*/
