# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                         PLAYBOOK FOR BOM VALIDATION                         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

# Steps:
#   01) Process BOM (Validate and Extract)
#

- hosts:          localhost

  name:           BOM Validator
  gather_facts:   true
  connection:     local
  become:         false
  become_user:    root

  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here.
#
# -------------------------------------+---------------------------------------8

    - name: Initialize facts
      set_fact:
        tier:     preparation

    - name: Run the bom-validator
      include_role:
        name:     roles-sap/0.1-bom-validator


...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
