# /*----------------------------------------------------------------------------8
# |                                                                             |
# |       Playbook for performing general baseline OS configuration tasks       |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---

# --------------------------------------+---------------------------------------8
#
# <Comment Header> 
#
# --------------------------------------+---------------------------------------8

- hosts:              "{{ sap_sid|upper }}_DB  :
                       {{ sap_sid|upper }}_SCS :
                       {{ sap_sid|upper }}_PAS :
                       {{ sap_sid|upper }}_APP :
                       {{ sap_sid|upper }}_WEB"

  name:               OS - Base Configuration
  remote_user:        "{{ orchestration_ansible_user }}"                
  become:             yes
  become_user:        root
  gather_facts:       true
  any_errors_fatal:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:

  # - name: Test Connection                                     # Simple connection test for troubleshooting
  #   ping:

# TODO: sudoers Config

  - include_role:
      name:     roles-os/os-swap                                # TODO: Centiq copy (rework needed)

  - include_role:
      name:     roles-os/hostname                               # TODO: Review and Refactoring Needed

  - include_role:
      name:     roles-os/repository                             # TODO: Review and Refactoring Needed

  - include_role:
      name:     roles-os/preparation                            # TODO: Review and Refactoring Needed

  - include_role:
      name:     roles-os/prometheus                             # TODO: Review and Refactoring Needed
    when:   prometheus

  # - debug:
  #     var: hostvars['x00scs00l373']

#----------------------------------------
# BEGIN
#
# TODO: evaluate for inclusion and refactor.
# SOURCE: sap-playbook
#----------------------------------------


#----------------------------------------
# BEGIN
#
# TODO: evaluate and refactor. move to os_base_config and os_sap_config
#----------------------------------------


# # Prepare os, disks and mount points on Hana Database servers
# # - hosts: hanadbnodes
# - hosts: X00_DB
#   become: true
#   become_user: root
#   vars_files:
#     - "vars/packages.yaml"
#   pre_tasks:
#     - name: Include SAP HANA DB sizes
#       include_vars:
#         file: "{{ configs_path }}/hdb_sizes.json"
#         name: hdb_sizes
#   max_fail_percentage: 0
#   roles:
#     - role: os-preparation
#     - role: os-disk-setup
#     - role: enable-prometheus
#       when:
#         - output.options.enable_prometheus == True
#         - ansible_facts['distribution_file_variety'] == 'SUSE'
#         - ansible_facts['distribution_version'] is regex("(12\.[3-5]|15\.\d)")
#         - hana_database.size != "LargeInstance"

#----------------------------------------
# END
#----------------------------------------






...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
