# /*---------------------------------------------------------------------------------------------------8
# |                                                                                                    |
# |                      Playbook for SAP SCS HA Install and Pacemkaer config of HANA                  |
# |                                                                                                    |
# +------------------------------------4--------------------------------------------------------------*/
---
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here.
#
# -------------------------------------+---------------------------------------8

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                       Retrieving the SPN details                           |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- hosts: localhost
  name: Get SPN from KeyVault
  remote_user:    "{{ orchestration_ansible_user }}"
  become:         false
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults
  tasks:
    - name: Initialize tier
      ansible.builtin.set_fact:
        tier:  fencing

    # - ansible.builtin.debug:
    #     msg: "Currently running in Tier: {{ tier }}"

    - name: Run the keyvault role
      include_role:
        name:     roles-misc/0.2-kv-secrets
      tags:
        - kv-secrets

    - name: Run the password role
      include_role:
        name:     roles-misc/0.1-passwords
        public:   true
      tags:
        - 0.1-passwords

    # - ansible.builtin.debug:
    #     msg: "Currently finishing in Tier: {{ tier }}"

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |              Playbook for SAP SCS HA and Pacemaker Resources               |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- hosts:          "{{ sap_sid|upper }}_SCS :
                   {{ sap_sid|upper }}_ERS"
  name:           "SCS HA Install and Pacemaker Resources"
  remote_user:    "{{ orchestration_ansible_user }}"
  become:         true
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults

  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here.
#
# -------------------------------------+---------------------------------------8
    - name: Print the fencing tenant id
      debug:
        msg: "{{ hostvars.localhost.sap_fencing_spn_tenant_id }}"

    - name: Initialize facts
      set_fact:
        tier:                                      ha
        password_ha_db_cluster:                    "{{ hostvars.localhost.db_cluster_password }}"
        main_password:                             "{{ hostvars.localhost.sap_password }}"
        primary_instance_name:                     "{{ ansible_play_hosts_all[0] }}"         # Setting up Primary Instance Name
        secondary_instance_name:                   "{{ ansible_play_hosts_all[1] }}"         # Setting up Secondary Instance Name
        #sap_hana_fencing_spn_client_id:            "{{ hostvars.localhost.sap_fencing_spn_client_id }}"
        #sap_hana_fencing_spn_client_pwd:           "{{ hostvars.localhost.sap_fencing_spn_pwd }}"
        #sap_hana_fencing_spn_tenant_id:            "{{ hostvars.localhost.sap_fencing_spn_tenant_id }}"
      tags:
        - always

    
      
    - block:
        - name:                                    Run the pacmaker role
          include_role:
            name:                                  roles-sap/5.6-scsers-pacemaker
          when:                                    scs_high_availability
      tags:
        - 5.6-scsers-pacemaker


- hosts: localhost
  name: Log results
  remote_user:    "{{ orchestration_ansible_user }}"
  become:         false
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults
  tasks:
    - name: Ensure the step file exists
      ansible.builtin.file:
        path: "{{ _workspace_directory }}/.step601"
        state: touch
        mode:  0755

...


# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +------------------------------------4--------------------------------------*/
