# /*----------------------------------------------------------------------------8
# |                                                                             |
# |                      Playbook for HANA DB Install                           |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---

- hosts:        scs                                   # TODO: Replace this with new inventory group; Change to correct group
  name:         DB Installation - HANA
  remote_user:  azureadm                              # TODO: Replace with variable
  become:       yes
  become_user:  root
  vars_files:
    - vars/ansible-input-api.yaml                     # DONE: move this back into Repo Structure as an API template


  tasks:

  - name: Test Connection                             # TODO: Temp place holder
    ping:




#----------------------------------------
# BEGIN
#
# TODO: evaluate for inclusion and refactor.
# SOURCE: sap-playbook
#----------------------------------------

# --------------------------------------+---------------------------------------8
#
# <Comment Header> 
#
# --------------------------------------+---------------------------------------8


#----------------------------------------
# BEGIN: Commented Section to enable BOM
#        Process
#
# TODO: evaluate and refactor. DB install, HSR, HA
#----------------------------------------

# # Hana DB components install
# - hosts: hanadbnodes
#   become: true
#   become_user: root
#   any_errors_fatal: true
#   vars_files:
#     - "vars/ha-packages.yaml"
#   pre_tasks:
#     - name: Include SAP HANA DB sizes
#       include_vars:
#         file: "{{ configs_path }}/hdb_sizes.json"
#         name: hdb_sizes
#   roles:
#     - role: hdb-server-install

#----------------------------------------
# END
#----------------------------------------





...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
