# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                       Playbook for SAP SCS Install                         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

# TODO: Playbook not yet written

- hosts:          "{{ sap_sid|upper }}_SCS"

  name:           SAP Installation - SCS
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                                               # API Input template with defaults


  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8

  - ansible.builtin.set_fact:
      tier:     scs
    tags:
      - always

# -------------------------------------+---------------------------------------8
# Role: 2.5-sap-users
#
# Description: Create Users for SAP
#              Create Users for SAP
#
  - include_role:
      name:     roles-sap-os/2.5-sap-users
    
# -------------------------------------+---------------------------------------8

  - include_role:
      name:     roles-sap/5.0.0-scs-install


...
# /*---------------------------------------------------------------------------8
# |                                    END                                     |
# +------------------------------------4--------------------------------------*/
