---

- hosts: localhost
  vars:
    bom_location_base_path: "../../documentation/ansible/system-design-deployment/examples"
    bom_base_name: "S4HANA_2020_ISS_v001"
    test_mode: true

  roles:

    - role: process_bom
      vars:
        base_bom: "{{ bom_location_base_path }}/{{ bom_base_name }}/bom.yml"
