---

- hosts: hanadbnodes
  become: true
  become_user: root
  vars:
    disk_dict: {}
    hana_components: ['server']
    start: 0
    azure_files_mount_path: "/sapmnt"
    hana_install_path: "/hana/shared/install"
    hana_software_loc: "{{ azure_files_mount_path }}/DB/DATA_UNITS/HDB_SERVER_LINUX_X86_64"
  vars_files: 
     - "vars/packages.yml" 
  pre_tasks:
    - name: Include SAP HANA DB sizes
      include_vars:
        file: ../hdb_sizes.json
        name: hdb_sizes

    - name: Include output JSON
      include_vars:
        file: "/home/{{ ansible_user }}/output.json"
        name: output

    - name: Create dictionary with HANA database information from output.JSON
      set_fact: 
        hana_database: "{{ item }}"
      loop: "{{ output.databases|flatten(levels=1) }}"
      when: item.platform == 'HANA'
  roles:
    - { role: os-preparation }
    - { role: os-disk-setup }
    - { role: sap-media-download }
    - { role: sap-hdb-xsa-install }

- hosts: linux-jumpboxes
  become: true
  become_user: root
  vars:
    azure_files_mount_path: "/sapmnt"
    hdbstudio_install_path: "/usr/sap/hanastudio"
    hdbstudio_software_loc: "{{ azure_files_mount_path }}/DB/DATA_UNITS/HDB_STUDIO_LINUX_X86_64"
    hdbstudio_template_path: "/usr/sap"
  pre_tasks:
    - name: Include output JSON
      include_vars:
        file: "/home/{{ ansible_user }}/output.json"
        name: output

    - name: Create dictionary with Linux Jumpbox information from output.JSON
      set_fact:
        linux_jumpbox: "{{ item }}"
      loop: "{{ output.jumpboxes.linux|flatten(levels=1) }}"
      when: item.name == 'jumpbox-linux'
  roles:
    - { role: hana-studio-linux-install, when: '"hana_studio_linux" in linux_jumpbox.components' }
