# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                         PLAYBOOK FOR BOM VALIDATION                         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

# Steps:
#   01) Process BOM (Validate and Extract)
#

- hosts:          localhost

  name:           Tester
  gather_facts:   false
  
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8

  - ansible.builtin.set_fact:
      tier:     hdb

  - include_role:
      name:     roles-misc/0.1-passwords


...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
