---

# Mount Azure Files on all Linux VMs
 
- name: Create list of hosts to mount Azure file
  set_fact: 
     host_list: "['{{ item }}'] + ['localhost']"
  with_items: "{{ groups['hanadbnodes'] }}"

- name: Create azure fileshare credentials directory
  file:
    path: "/etc/smbcredentials"
    state: directory
  delegate_to: "{{ item }}"
  with_items: "{{ host_list }}"

- name: Create azure fileshare mount directory
  file:
    path: "{{ azure_files_mount_path }}"
    state: directory
  delegate_to: "{{ item }}"
  with_items: "{{ host_list }}"

- name: Create credentials file
  copy:
    content: |
      username={{ output.software.storage_account_sapbits.container_name }}
      password={{ output.software.storage_account_sapbits.storage_access_key }}
    dest: /etc/smbcredentials/{{ output.software.storage_account_sapbits.container_name }}.cred
    mode: 600
  delegate_to: "{{ item }}"
  with_items: "{{ host_list }}"

- name: Mount storage for SAP bits on RTI and DB nodes
  mount:
    path: "{{ azure_files_mount_path }}"
    fstype: cifs
    opts: "credentials=/etc/smbcredentials/{{ output.software.storage_account_sapbits.container_name }}.cred,dir_mode=0755,file_mode=0755,serverino,defaults,nofail,vers=3.0"
    src: "//{{ output.software.storage_account_sapbits.container_name }}.file.core.windows.net/sapmnt"
    state: mounted
  delegate_to: "{{ item }}"
  with_items: "{{ host_list }}"
