# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                      Playbook for PACEMAKER config of HANA                  |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

- hosts:          "{{ sap_sid|upper }}_DB" 

  name:           PACEMAKER - HANA
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults
  
  tasks:


# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8


# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +------------------------------------4--------------------------------------*/

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                       Retrieving the SPN details                           |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- hosts: localhost
  name: Get SPN from KeyVault
  remote_user:    "{{ orchestration_ansible_user }}"
  become:         no
  become_user:    root
  gather_facts:   yes
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults
  tasks:
  - ansible.builtin.set_fact:
      tier:  fencing

  # - ansible.builtin.debug:
  #     msg: "Currently running in Tier: {{ tier }}"
  
  - include_role:
      name:     roles-misc/0.2-kv-secrets
    tags:
       - kv-secrets

  - include_role:
      name:     roles-misc/0.1-passwords
      public:   yes      
    tags:
       - 0.1-passwords
  
  # - ansible.builtin.debug:
  #     msg: "Currently finishing in Tier: {{ tier }}"

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                       Playbook for Pacemaker -HANA                         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/


- hosts:          "{{ sap_sid|upper }}_DB"
  name:           "PACEMAKER - HANA"
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults

  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8
  - debug:
      msg: "{{ hostvars.localhost.sap_fencing_spn_tenant_id }}"

  - set_fact:
      tier:                                      ha
      hana_password_master:                      "{{ hostvars.localhost.sap_password }}"
      primary_instance_name:                     "{{ ansible_play_hosts_all[0] }}"         # Setting up Primary Instance Name
      secondary_instance_name:                   "{{ ansible_play_hosts_all[1] }}"         # Setting up Secondary Instance Name
      sap_hana_fencing_spn_client_id:            "{{ hostvars.localhost.sap_fencing_spn_client_id }}"
      sap_hana_fencing_spn_client_pwd:           "{{ hostvars.localhost.sap_fencing_spn_pwd }}"
      sap_hana_fencing_spn_tenant_id:            "{{ hostvars.localhost.sap_fencing_spn_tenant_id }}"
    tags:
      - always

  - block:
      - include_role:
          name:     roles-os/1.11-accounts
          tasks_from: setup_hanausers_sudoers.yml
    tags:
      - 1.11-accounts
  - block:
      - include_role:
          name:     roles-sap/5.5-hanadb-pacemaker
        when: db_high_availability == true          
    tags:
      - 5.5-hanadb-pacemaker

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                       Logging the results                                  |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

# - hosts: localhost
#   name: Get SPN from KeyVault
#   remote_user:    "{{ orchestration_ansible_user }}"
#   become:         no
#   become_user:    root
#   gather_facts:   yes
#   vars_files:
#     - vars/ansible-input-api.yaml                               # API Input template with defaults
#   tasks:
#   - ansible.builtin.set_fact:
#       tier:  fencing

#   - include_role:
#       name:     roles-misc/0.2-kv-secrets
#     tags:
#        - kv-secrets

- hosts: localhost
  name: Log results
  remote_user:    "{{ orchestration_ansible_user }}"
  become:         no
  become_user:    root
  gather_facts:   yes
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults
  
  tasks:
  - ansible.builtin.file:
      path: "{{ _workspace_directory }}/.step603"
      state: touch


...


# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +------------------------------------4--------------------------------------*/
