# /*----------------------------------------------------------------------------8
# |                                                                             |
# |                       Role for downloading the BOM                          |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---
# --------------------------------------+---------------------------------------8
#
# <Comment Header> 
#
# --------------------------------------+---------------------------------------8
# TODO: 20210127 Review

- name:   Check required variables are present and not empty
  assert:
    that:
      - "sapbits_location_base_path is defined"
      - "sapbits_location_base_path | trim | length != 0"

      - "sapbits_bom_files is defined"
      - "sapbits_bom_files | trim | length != 0"

      - "bom_base_name is defined"
      - "bom_base_name | trim | length != 0"

      - "target_media_location is defined"
      - "target_media_location | trim | length != 0"


#----------------------------------------
# BEGIN - OLD CODE
#----------------------------------------

# - include_tasks: pre_checks.yaml

- include_tasks: ensure-bom.yaml
