trigger: none
pr:
  branches:
    include:
    - feature/*
  paths:
    include:
    - deploy/terraform/run/sap_system/*
    - deploy/terraform/terraform-units/modules/sap_system/*
variables:
  - group: azure-config-variables
  - group: azure-sap-hana-pipeline-secrets
  - template: templates/variables.yaml
stages:
- stage:
  pool:
    vmImage: "ubuntu-18.04"
  variables:
    ssh_timeout_s: 120
  jobs:
  - job: createSAPSystem
    steps:
      - template: templates/util/prepare-agent.yml
      - template: templates/util/collect-deployer-info.yml
        parameters:
          deployer_rg_name: "unit-eaus-deployer-infrastructure"
      - template: templates/util/add-agent-to-deployer-nsg.yml
        parameters:
          deployer_rg_name: "unit-eaus-deployer-infrastructure"
      - template: templates/sapsystem/create-sapsystem-steps.yml
        parameters:
          branch_name: $(targetBranchName)
          deployer_rg_name: "unit-eaus-deployer-infrastructure"
          sapsystem_rg_name: "$(Build.BuildId)-eaus-sap0-PRD"
      - template: templates/sapsystem/validate-sapsystem-steps.yml
        parameters:
          branch_name: $(sourceBranchName)
          sapsystem_rg_name: "$(Build.BuildId)-eaus-sap0-PRD"
      - template: templates/sapsystem/create-sapsystem-steps.yml
        parameters:
          branch_name: $(sourceBranchName)
          deployer_rg_name: "unit-eaus-deployer-infrastructure"
          sapsystem_rg_name: "$(Build.BuildId)-eaus-sap0-PRD"
      - template: templates/util/remove-agent-from-deployer-nsg.yml
        parameters:
          deployer_rg_name: "unit-eaus-deployer-infrastructure"
  - job: deleteSAPSystem
    dependsOn: createSAPSystem
    condition: or(succeededOrFailed(), always())
    steps:
      - template: templates/util/prepare-agent.yml
      - template: templates/util/collect-deployer-info.yml
        parameters:
          deployer_rg_name: "unit-eaus-deployer-infrastructure"
      - template: templates/util/add-agent-to-deployer-nsg.yml
        parameters:
          deployer_rg_name: "unit-eaus-deployer-infrastructure"
      - template: templates/sapsystem/delete-sapsystem-steps.yml
        parameters:
          branch_name: $(sourceBranchName)
          deployer_rg_name: "unit-eaus-deployer-infrastructure"
          sapsystem_rg_name: "$(Build.BuildId)-eaus-sap0-PRD"
      - template: templates/util/remove-agent-from-deployer-nsg.yml
        parameters:
          deployer_rg_name: "unit-eaus-deployer-infrastructure"
