# /*----------------------------------------------------------------------------8
# |                                                                             |
# |            Role for ensuring the hostname is configured correctly           |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---
# --------------------------------------+---------------------------------------8
#
# <Comment Header> 
#
# --------------------------------------+---------------------------------------8
# TODO: 20210127 Review

#----------------------------------------
# BEGIN - OLD CODE
#----------------------------------------

# # Implement manual preparation steps for OS
# # The name for all sub tasks follows <OS type>-<OS version>/os_config.yml naming conversion

# - name: Manual preparation for all OS
#   include_tasks: "common/os_config.yml"

# # Currently we only support RHEL-7
# - name: Manual preparation for RedHat
#   include_tasks: "{{ ansible_os_family }}/RHEL-{{ ansible_distribution_major_version }}/os_config.yml"
#   when:  ansible_os_family == "RedHat"

# # Currently we only support SLES-12
# - name: Manual preparation for Suse
#   include_tasks: "{{ ansible_os_family }}/SLES-{{ ansible_distribution_major_version }}/os_config.yml"
#   when:  ansible_os_family == "Suse"

#----------------------------------------
# END  - OLD CODE
#----------------------------------------



# Implement manual preparation steps for all OS
# The tasks' name follows:
#   - SAP Notes for RHEL OS recommendations

# RHEL-3.10 Disable Transparent Hugepages (THP)
# RHEL-3.12 Configure Processor C-States (not relevant for IBM Power LE (ppc64le))
# SAP Note 2205917 - SAP HANA DB Recommended OS settings for SLES 12 / SLES for SAP Applications 12
- name:     Task Disable Transparent Hugepages & Configure Processor C-States 1
  command:    "echo never > /sys/kernel/mm/transparent_hugepage/enabled"

- name:     Task Disable Transparent Hugepages & Configure Processor C-States 2
  lineinfile: 
     dest:    /etc/default/grub 
     regexp:  "GRUB_CMDLINE_LINUX=" 
     line:    "GRUB_CMDLINE_LINUX='crashkernel=auto  @ vconsole.keymap=us @kernel_arguments: transparent_hugepage=never intel_idle.max_cstate=1 processor.max_cstate=1'"

- name:     Task Disable Transparent Hugepages & Configure Processor C-States 3
  command:    grub2-mkconfig -o /boot/grub2/grub.cfg


- name:     Include variable file
  include_vars:   ../../../vars/packages.yaml


# Currently we only support RHEL-7 or SLES-12
- name:     "Manual preparation for {{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}"
  include_tasks:    "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}-os_config.yml"
  when:     ansible_os_family|upper == "REDHAT" or
            ansible_os_family|upper == "SUSE"



...