---
# Assumptions
#   target_media_location exists on disk
#
# Inputs:
#   target_media_location             Default     /usr/sap/install
#   download_directory
#   bom_name
#   sapbits_location_base_path
#   sapbits_bom_files
#   sapbits_sas_token
#
# Locals:
#   _bom
#   item
#   result
#
# BOM Fields:
#   download
#   archive
#   permissions
#   


# Steps:
#   01) Register BOM
#   02) Validate media from bom

#   01) Register BOM
- name:         "Register BOM: {{ bom_name }}"
  include_vars:
    file:       "{{ download_directory }}/bom/{{ bom_name }}.yaml"
    name:       _bom

#------------------<DEBUGGING>-------------------
# - debug:  
#     msg:      "Archive: {{ item.archive }} Url: {{ item.url }} Dest: {{ download_directory }}/{{ item.archive }}"
#   loop:       "{{ bom.materials.media|flatten(levels=1) }}"
#------------------</DEBUGGING>------------------


# Files to download
#------------------<DEBUGGING>-------------------
# - debug:  
#     msg:      
#       - "URL : {{ item.url }}"
#   loop:       "{{ bom.materials.media|flatten(levels=1) }}"
#------------------</DEBUGGING>------------------



#   02) Validate media from SAP
# Loop through BOM media files 
# - name: "BOM: Check/Download Files"
#   get_url:
#     url:              "{{ item.url }}"
#     dest:             "{{ download_directory }}/bom/{{ item.archive }}"
#     tmp_dest:         "{{ download_directory }}/tmp"
#     url_username:     "{{ S_user }}"
#     url_password:     "{{ S_password }}"
#     force_basic_auth: yes
#     http_agent:       'SAP Software Download'
  
#   register: result
#   until:    result is succeeded
#   retries:  2
#   delay:    1
#   loop:     "{{ _bom.materials.media|flatten(levels=1) }}"
#   when:     item.url is defined

- debug: 
    msg: "aaa"
#   03) Upload files to Azure
# Loop through BOM media files 
#  shell: "az storage blob upload --account-name kfosapuploader --account-key jSGZcd90xpW9DvSE+fE3hfSrGr1SDrCYz/3eCDPw3XT0LRdo7oYPQGdmFFI28SenFWAVgZbWYp2YIwr61qb0og== --container-name bits --name {{ item.archive }}  --file {{ download_directory }}/bom/{{ item.archive }} --if-none-match \"*\""
- name: "BOM: Upload files"
  shell: "az storage blob upload --account-name kfosapuploader --account-key jSGZcd90xpW9DvSE+fE3hfSrGr1SDrCYz/3eCDPw3XT0LRdo7oYPQGdmFFI28SenFWAVgZbWYp2YIwr61qb0og== --container-name bits --name SOLMAN72FPS12_v0001ms.yaml --file {{ download_directory }}/bom/SOLMAN72FPS12_v0001ms.yaml --if-none-match \"*\""
  register: azresult

- debug: 
    var: azresult



# -------------------------------------+---------------------------------------8

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/

