---

- name:                                "BOM: {{ bom_name }} Download File {{ item.archive }}"
  ansible.builtin.get_url:
    url:                               "{{ item.url }}"
    dest:                              "{{ download_directory }}/files/{{ item.archive }}"
    tmp_dest:                          "{{ download_directory }}/tmp"
    url_username:                      "{{ s_user }}"
    url_password:                      "{{ s_password }}"
    force_basic_auth:                  true
    http_agent:                        'SAP Software Download'

  become:                              true
  become_user:                         root
  register:                            result
  until:                               result is succeeded
  retries:                             2
  delay:                               1
  no_log:                              false

#   03) Upload files to Azure
- name:                                "BOM: {{ bom_name }} Upload File {{ item.archive }}"

  ansible.builtin.command: >-
                                       "az storage blob upload
                                         --account-name {{ sapbits_location_base_path.rpartition('//')[2].split('.')[0] }}
                                         --account-key {{ sapbits_access_key }}
                                         --container-name {{ sapbits_location_base_path.rpartition('//')[2].split('/')[1] }}/{{ sapbits_bom_files }}/archives
                                         --name {{ item.archive }}
                                         --file {{ download_directory }}/files/{{ item.archive }}
                                         --if-none-match "*"
                                         --no-progress"
  delegate_to:                         localhost
  register:                            azresult
  ignore_errors:                       true
  failed_when:                         
   - azresult.rc != 0 
   - azresult.stderr is defined
   - azresult.stderr.find("BlobAlreadyExists") == -1
  when:
    - item.archive is defined


...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
