---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |          Retrieve or create the SAP cluster password from keyvault         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                Construct SAP db cluster password secret name
  ansible.builtin.set_fact:
    cluster_password_id:               "{{ secret_prefix }}-{{ sap_sid }}-sap-db-cluster-password"

- name:                                "Create Password secret"
  ansible.builtin.command:             az keyvault secret set --vault-name {{ kv_name }} --name {{ cluster_password_id }} --value "{{ password_ha_db_cluster }}"
  when:
    - password_ha_db_cluster is defined
    - "password_ha_db_cluster | trim | length != 0"

- name:                                "SAP db cluster password secret name"
  ansible.builtin.debug:
    var:                               cluster_password_id
    verbosity:                         2

- name:                                "Retrieve SAP db cluster password"
  block:
    - name:                            "Get SAP db cluster password from keyvault"
      ansible.builtin.command: >-
                                       az keyvault secret show
                                         --vault-name {{ kv_name }}
                                         --name {{ cluster_password_id }}
      changed_when:                    false
      register:                        keyvault_secret_show_db_cluster_password_id
      no_log:                          false
  rescue:
    - name:                            "Performing rescue action"
      ansible.builtin.debug:
        msg:                           "{{ keyvault_secret_show_db_cluster_password_id.rc }}"

    - name:                            Remove tmp file
      ansible.builtin.file:
        path:                          /tmp/sappasswordfile
        state:                         absent

    - name:                            Construct SAP system password
      ansible.builtin.set_fact:
        sap_db_cluster_password:       "{{ lookup('password', '/tmp/sappasswordfile length=12 chars=ascii_letters,hexdigits') }}"
      when:                            3 == keyvault_secret_show_db_cluster_password_id.rc

    - name:                            "Debug: SAP cluster Password"
      ansible.builtin.debug:
        var:                           sap_db_cluster_password
        verbosity: 2
      when:                            3 == keyvault_secret_show_db_cluster_password_id.rc

    - name:                            "Create Password secret"
      ansible.builtin.command: >-
                                       az keyvault secret set
                                        --vault-name {{ kv_name }}
                                        --name {{ cluster_password_id }}
                                        --value "{{ sap_db_cluster_password }}"
      when:                            3 == keyvault_secret_show_db_cluster_password_id.rc

    - name:                            "Get SAP password from keyvault"
      ansible.builtin.command: >-
                                       az keyvault secret show
                                         --vault-name {{ kv_name }}
                                         --name {{ cluster_password_id }}
      changed_when:                    false
      register:                        keyvault_secret_show_db_cluster_password_id
      no_log:                          false

- name:                                "Extract SAP password"
  ansible.builtin.set_fact:
    db_cluster_password: >-
                                       {{ (keyvault_secret_show_db_cluster_password_id.stdout | from_json).value }}
  no_log:                              false

- name:                                "Debug: SAP cluster Password"
  ansible.builtin.debug:
    var:                               sap_db_cluster_password
    verbosity: 2
