---

# Install HANA database and XSA Components

- name: Create install directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ hana_install_path }}"
    - "{{ hana_install_path }}/SAP_HANA_DATABASE"

- name: Create SAP components list  
  set_fact: 
    hana_components: "{{ hana_components }} + ['xs']"
  loop: "{{ hana_database.components|flatten(levels=1) }}"
  when: item.name == 'XSA'

- name: Create dictionary with XSA inforamtion from output.JSON
  set_fact:
    xsa: "{{ item }}"
  loop: "{{ hana_database.components|flatten(levels=1) }}"
  when: item.name == 'XSA'

- name: Create install template for SAP HANA 1.0
  template:
    src:  hdbserver_hana1.j2 
    dest: "{{ hana_install_path }}/hdbserver_{{ hana_database.instance.sid }}_install.cfg"
  when: hana_database.db_version is regex("1([0-9]\d|[0-9]\d{2}).\d{2}")  

- name: Create install template for SAP HANA 2.0
  template:
    src: hdbserver_hana2.j2 
    dest: "{{ hana_install_path }}/hdbserver_{{ hana_database.instance.sid }}_install.cfg"
  when: hana_database.db_version is regex("2.\d{2}.0([4-9]\d|[0-9]\d{2,})") 

- name: Create password file for hdblcm installer
  template:
    src: hdbserver_passwords.j2
    dest: "{{ hana_install_path }}/hdbserver_{{ hana_database.instance.sid }}_passwords.xml"

- name: Install HANA DB and XSA using hdblcm
  shell: "pwd=$(<../hdbserver_{{ hana_database.instance.sid }}_passwords.xml); echo $pwd | {{ hana_software_loc }}/hdblcm --sid={{ hana_database.instance.sid }} --batch --action=install --configfile='../hdbserver_{{ hana_database.instance.sid }}_install.cfg' --read_password_from_stdin=xml"
  args:
    chdir: "{{ hana_install_path }}/SAP_HANA_DATABASE"
