---

- name: Install packages
  apt: 
    name: unzip
    state: latest
    force_apt_get: yes
  delegate_to: localhost
 
- name: Create list of hosts to mount Azure file
  set_fact: 
     host_list: "['{{ item }}'] + ['localhost']"
  with_items: "{{ groups['hanadbnodes'] }}"

- name: Create azure fileshare credentials directory
  file:
    path: "/etc/smbcredentials"
    state: directory
  delegate_to: "{{ item }}"
  with_items: "{{ host_list }}"

- name: Create azure fileshare mount directory
  file:
    path: "{{ azure_files_mount_path }}"
    state: directory
  delegate_to: "{{ item }}"
  with_items: "{{ host_list }}"

- name: Create credentials file
  copy:
    content: |
      username={{ output.software.storage_account_sapbits.name }}
      password={{ output.software.storage_account_sapbits.storage_access_key }}
    dest: /etc/smbcredentials/{{ output.software.storage_account_sapbits.name }}.cred
    mode: 600
  delegate_to: "{{ item }}"
  with_items: "{{ host_list }}"

- name: Mount storage for SAP bits on RTI and DB nodes
  mount:
    path: "{{ azure_files_mount_path }}"
    fstype: cifs
    opts: "credentials=/etc/smbcredentials/{{ output.software.storage_account_sapbits.name }}.cred,dir_mode=0755,file_mode=0755,serverino,defaults,nofail,vers=3.0"
    src: "//{{ output.software.storage_account_sapbits.name }}.file.core.windows.net/sapmnt"
    state: mounted
  delegate_to: "{{ item }}"
  with_items: "{{ host_list }}"

- name: Download pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /usr/bin/get-pip.py
  delegate_to: localhost

- name: Install Pip
  command: |
    python3 /usr/bin/get-pip.py
  delegate_to: localhost

- name: Install beautifulsoup4
  pip:
    name: beautifulsoup4
    state: latest
    executable: pip3
  delegate_to: localhost

- name: Create HDB json with SAP bits with credentials
  template:
    src: hdb_json.j2 
    dest: "../python_scripts/downloader/hdb.json"
  delegate_to: localhost

- name: Download bits
  shell: "python3 ../python_scripts/downloader/basket.py --config ../python_scripts/downloader/hdb.json --dir {{ azure_files_mount_path }}"
  delegate_to: localhost

- name: Find bits zipfile name
  command: "ls {{ azure_files_mount_path }}/DB"
  register: bits_file
  delegate_to: localhost

- name: Unzip Downlaod bitsfile
  unarchive: 
    src: "{{ azure_files_mount_path }}/DB/{{bits_file.stdout}}"
    dest: "{{ azure_files_mount_path }}/DB"
    remote_src: yes
  delegate_to: localhost 
