---

- name: Ensure key files are in place
  # If HSR is already enabled, we don't need to do this
  when: not hana_system_replication_enabled
  block:

    - name: Ensure the secondary node SSFS files are backed up and removed
      when: ansible_hostname != hana_database.nodes[0].dbname
      block:

        - name: Ensure {{ path_ssfs_dat }} file is copied
          import_tasks: copy_ssfs_key_path.yml
          vars:
            ssfs_file_path: "{{ path_ssfs_dat }}"

        - name: Ensure {{ path_ssfs_key }} file is copied
          import_tasks: copy_ssfs_key_path.yml
          vars:
            ssfs_file_path: "{{ path_ssfs_key }}"

        - name: Ensure {{ path_xsa_ssfs_dat }} file is copied
          import_tasks: copy_ssfs_key_path.yml
          vars:
            ssfs_file_path: "{{ path_xsa_ssfs_dat }}"

        - name: Ensure {{ path_xsa_ssfs_key }} file is copied
          import_tasks: copy_ssfs_key_path.yml
          vars:
            ssfs_file_path: "{{ path_xsa_ssfs_key }}"
