---

    # HANA must be restarted after setting values in global.ini
  - name: Ensure options set in section [inifile_checker] of global.ini.
    ini_file:
      path: "{{ path_global_ini }}"
      section: inifile_checker
      state: present
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    with_items:
      - option: enable
        value: "true"
      - option: interval
        value: "3600"
      - option: replication
        value: "true"
