
- name: Set the NFS Server name
  ansible.builtin.set_fact:
    nfs_server: "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_SCS') | first }}"

- name: "Mount: Disable ID mapping (ANF)"
  ansible.builtin.lineinfile:
    path:   /etc/idmapd.conf
    regexp: '^[ #]*Domain = '
    line:   ' Domain = defaultv4iddomain.com'
    insertafter: '[General]'
  register: autofs_mapping_changed
  when:     tier == 'sapos' 

- name:     "Mount: Ensure the  services is restarted"
  block:
    - name: "Mount: Ensure the rpcbind service is restarted" 
      ansible.builtin.systemd:
        name: rpcbind
        state: restarted
    - name: "Mount: Clear the cache of the nfsidmap daemon (ANF)"
      ansible.builtin.shell: |
                      sleep 10
                      nfsidmap -c

  when: autofs_mapping_changed is changed 

- name: "Mount: Create /saptmp (ANF)"
  ansible.builtin.file:
    path:        "/saptmp"
    state:       directory

    # group:       sapsys
    # owner:       "{{ sap_sid|lower }}adm"
    # attributes:  "+i"

- name: "Mount: Create SAP Directories (ANF)"
  ansible.builtin.file:
    path:        "{{ item.path }}"
    state:       directory
    mode:        0755
  loop:
    - { tier == 'sapos', path: '/saptmp/sapmnt{{ sap_sid|upper }}' }
    - { tier == 'sapos', path: '/saptmp/usrsap{{ sap_sid|upper }}ascs' }
    - { tier == 'sapos', path: '/saptmp/usrsap{{ sap_sid|upper }}ers' }
    - { tier == 'sapos', path: '/saptmp/usrsap{{ sap_sid|upper }}sys' }
    - { tier == 'sapos', path: '/saptmp/usrsap{{ sap_sid|upper }}pas' }
    - { tier == 'sapos', path: '/saptmp/usrsap{{ sap_sid|upper }}aas' }
  when:     tier == 'sapos' and node_tier == 'scs'

  # Mount Filesystem on ANF
  # This is needed so that we can create the correct directory
- name:     "Mount: Filesystems on ANF"
  block:
    - name:     "Mount: Filesystems on ANF"
      ansible.builtin.mount:
        src:    "{{ sap_mnt }}"
        path:   "/saptmp"
        fstype: "nfs4"
        opts:   "rw,hard,rsize=65536,wsize=65536,sec=sys,vers=4.1,tcp"
        state:  mounted
  when:     tier == 'sapos' and node_tier == 'scs'
  rescue:
    - name: "Mount: Clear the cache of the nfsidmap daemon (ANF)"
      ansible.builtin.shell: |
                      nfsidmap -c
    - name: "Mount: Ensure the rpcbind service is restarted" 
      ansible.builtin.systemd:
        name: rpcbind
        state: restarted


- name:     "Mount: Unmount filesystems (ANF)"
  ansible.builtin.mount:
    src:    "{{ sap_mnt }}"
    path:   "/saptmp"
    fstype: "nfs4"
    opts:   "rw,hard,rsize=65536,wsize=65536,sec=sys,vers=4.1,tcp"
    state:  unmounted
  when:     tier == 'sapos' and node_tier == 'scs'

- name: "Mount: Delete locally created SAP Directories (ANF)"
  ansible.builtin.file:
    path:       "{{ item.path }}"
    state:      absent
    mode:       0755
  loop:
    - { tier == 'sapos', path: '/saptmp/sapmnt{{ sap_sid|upper }}' }
    - { tier == 'sapos', path: '/saptmp/usrsap{{ sap_sid|upper }}ascs' }
    - { tier == 'sapos', path: '/saptmp/usrsap{{ sap_sid|upper }}ers' }
    - { tier == 'sapos', path: '/saptmp/usrsap{{ sap_sid|upper }}sys' }
    - { tier == 'sapos', path: '/saptmp/usrsap{{ sap_sid|upper }}pas' }
    - { tier == 'sapos', path: '/saptmp/usrsap{{ sap_sid|upper }}aas' }
  when:     tier == 'sapos' and node_tier == 'scs'

- name:     "Mount: Cleanup fstab and directory (ANF)"
  ansible.builtin.mount:
    src:    "{{ sap_mnt }}"
    path:   "/saptmp"
    fstype: "nfs4"
    opts:   "rw,hard,rsize=65536,wsize=65536,sec=sys,vers=4.1,tcp"
    state:  absent
  when:     tier == 'sapos' and node_tier == 'scs'

# Configure Autofs
- name:                 "Mount: Create auto.master"
  ansible.builtin.lineinfile:
    state:              present
    dest:               /etc/auto.master
    line:               '/- /etc/auto.direct'
  when:     tier == 'sapos'

- name:                 "Mount: Create auto.direct"
  ansible.builtin.file:
    state:              touch
    path:               /etc/auto.direct
    mode:              '0644'
  when:     tier == 'sapos'

- name:                 "Mount: Update auto.direct (scs)"
  ansible.builtin.blockinfile:
    path: /etc/auto.direct
    block: |
              /sapmnt/{{ sap_sid|upper }} -nfsvers=4.1,nobind,sec=sys {{ sap_mnt }}/sapmnt{{ sap_sid|upper }}
              /usr/sap/{{ sap_sid|upper }}/SYS -nfsvers=4.1,nobind,sec=sys {{ sap_mnt }}/usrsap{{ sap_sid|upper }}sys
  when: node_tier == 'scs'
  register: autofs_configuration_changed_scs
  
- name:                 "Mount: Update auto.direct"
  ansible.builtin.blockinfile:
    path: /etc/auto.direct
    block: |
              /usr/sap/install -nfsvers=4.1,nobind,sec=sys {{ nfs_server }}:/usr/sap/install
              /sapmnt/{{ sap_sid|upper }} -nfsvers=4.1,nobind,sec=sys {{ sap_mnt }}/sapmnt{{ sap_sid|upper }}
              /usr/sap/{{ sap_sid|upper }}/SYS -nfsvers=4.1,nobind,sec=sys {{ sap_mnt }}/usrsap{{ sap_sid|upper }}sys
  when: node_tier != 'scs'
  register: autofs_configuration_changed

- name: "Mount: Ensure the Autofs service is restarted" 
  ansible.builtin.systemd:
    name: autofs
    state: restarted
  #when: autofs_configuration_changed is changed or autofs_configuration_changed_scs is changed

- name: "Mount: Ensure the NFS service is restarted" 
  ansible.builtin.systemd:
    name: nfsserver
    state: restarted
  when:  not distro_id == "redhat8" 
 
- name: "Mount: Ensure the NFS service is restarted RHEL" 
  ansible.builtin.systemd:
    name: nfs-server
    state: restarted
  when: distro_id == "redhat8"

# Configure shared direcotries
- name:     "Create the shared directories for SAP installation (ANF)"
  ansible.builtin.file:
    path:        "{{item.path}}"
    state:       directory
    #group:       sapsys
    #owner:       "{{ sap_sid|lower }}adm"
    attributes:  +i
  when: tier == 'sapos'
  loop:
    - { tier: 'sapos', path: '/sapmnt/{{ sap_sid|upper }}'     }
    - { tier: 'sapos', path: '/sapmnt/{{ sap_sid|upper }}/sys' }
  #TODO: Add to loop in near future
    #sudo mkdir -p /usr/sap/QAS/ASCS00
    #sudo mkdir -p /usr/sap/QAS/ERS01
