---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                                Admin Users                                 |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

# -------------------------------------+---------------------------------------8
# 'admin_accounts' specifies a list of hashes/dictionaries outlining the
# settings to be used when creating/managing admin groups
# -------------------------------------+---------------------------------------8

# Create User Groups for SAP:
#   sapsys - once defined, typically remains constant across all systems. Used
#   for file access in shared directories between SID's.
#
#   sapinst - typically only used durring install, and removed after. Potentially
#   can be depracated. 
# 


admin_groups:
  - { name:  sapsys,                   gid: "{{ sapsys_gid }}",  state: present, tier: sapos, enabled: true, node_tier: all }
  - { name:  sapinst,                  gid: "{{ sapinst_gid }}", state: present, tier: sapos, enabled: true, node_tier: all }
  - { name:  "{{ hdb_sid|lower }}shm", gid: "{{ hdbshm_gid }}",  state: present, tier: sapos, enabled: true, node_tier: all }

# -------------------------------------+---------------------------------------8
#
# 'admin_users' specifies a list of hashes/dictionaries outlining the
# settings to be used when creating/managing admin user accounts
#
# -------------------------------------+---------------------------------------8

admin_users:
  - { tier: sapos,   node_tier: all,                name: sapadm,                    uid: "{{ sapadm_uid }}", comment: "SAP Host Agent",                         enabled: true, group: sapsys,  groups: ["sapsys"],                            sudoers_role: "admin_no_password", shell: /bin/csh,  password: "{{ password_master }}", state: present }
  - { tier: sapos,   node_tier: [ scs, pas, app ],  name: "{{ sap_sid|lower }}adm",  uid: "{{ sidadm_uid }}", comment: "SAP System Administrator",               enabled: true, group: sapsys,  groups: ["sapsys"],                            sudoers_role: "admin_no_password", shell: /bin/csh,  password: "{{ password_master }}", state: present }
  - { tier: sapos,   node_tier: hana,               name: "{{ hdb_sid|lower }}adm",  uid: "{{ hdbadm_uid }}", comment: "SAP HANA Database System Administrator", enabled: true, group: sapsys,  groups: ["sapinst", "{{ hdb_sid|lower }}shm"], sudoers_role: "admin_no_password", shell: /bin/csh,  password: "{{ password_master }}", state: present }
  
