---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                                Admin Users                                 |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

# -------------------------------------+---------------------------------------8
# 'admin_accounts' specifies a list of hashes/dictionaries outlining the
# settings to be used when creating/managing admin groups
# -------------------------------------+---------------------------------------8

# Create User Groups for SAP:
#   sapsys - once defined, typically remains constant across all systems. Used
#   for file access in shared directories between SID's.
#
#   sapinst - typically only used durring install, and removed after. Potentially
#   can be depracated. 
# 


admin_groups:
  - name:         example
    gid:          "2000"
    state:        present
    tier:         example
    enabled:      true
    node_tier:    none
<<<<<<< HEAD
  - name:         sapsys
    gid:          "{{ sapsys_gid }}"
    state:        present
    tier:         ha
    enabled:      true
    node_tier:    all
  - name:         sapinst
    gid:          "2001"
    state:        present
    tier:         ha
    enabled:      true
    node_tier:    all
=======
#  - name:         sapsys
#    gid:          "{{ sapsys_gid }}"
#    state:        present
#    tier:         sapos
#    enabled:      true
#    node_tier:    all
#  - name:         sapinst
#    gid:          "2001"
#    state:        present
#    tier:         sapos
#    enabled:      true
#    node_tier:    all
>>>>>>> d4cf3b4b07f16988073e40fefe411c99f7d9ff93

# -------------------------------------+---------------------------------------8
#
# 'admin_users' specifies a list of hashes/dictionaries outlining the
# settings to be used when creating/managing admin user accounts
#
# -------------------------------------+---------------------------------------8

admin_users:
  - name:         example
    comment:      "Example User"
    uid:          "2000"
    group:        example
    groups:       ["users", "adm"]
    sudoers_role: "admin_no_password"
    shell:        /bin/bash
    password:     "some_password_string"
    state:        present
    tier:         example
    enabled:      true
    node_tier:    none
<<<<<<< HEAD
 
  # - name:         "{{ hdb_sid|lower }}adm"
  #   comment:      "SAP HANA Database System Administrator"
  #   uid:          "{{ hdbadm_uid }}"
  #   group:        sapsys
  #   groups:       ["sapsys"]
  #   password:     "{{ hana_password_master }}"
  #   sudoers_role: "hanaadmin_no_password"
  #   shell:        /bin/csh
  #   state:        present
  #   tier:         ha
  #   node_tier:    all
  #   enabled:      true
 
=======
>>>>>>> d4cf3b4b07f16988073e40fefe411c99f7d9ff93

#  - name:         sapadm
#   comment:      "SAP Host Agent"
#    uid:          "{{ sapadm_uid }}"
#    group:        sapsys
#    groups:       ["sapsys"]
#    password:     "some_password_string"
#    sudoers_role: "admin_no_password"
#    shell:        /bin/csh
#    state:        present
#    tier:         sapos
#    node_tier:    all
#    enabled:      true

#  - name:         "{{ sap_sid|lower }}adm"
#    comment:      "SAP System Administrator"
#    uid:          "{{ sidadm_uid }}"
#    group:        sapsys
#    groups:       ["sapsys"]
#    password:     "some_password_string"
#    sudoers_role: "admin_no_password"
#    shell:        /bin/csh
#    state:        present
#    tier:         sapos
#    node_tier:    all
#    enabled:      true

<<<<<<< HEAD
=======
#  - name:         "{{ hdb_sid|lower }}adm"
#    comment:      "SAP HANA Database System Administrator"
#    uid:          "{{ hdbadm_uid }}"
#    group:        sapsys
#    groups:       ["sapsys"]
#    password:     "some_password_string"
#    sudoers_role: "admin_no_password"
#    shell:        /bin/csh
#    state:        present
#    tier:         sapos
#    node_tier:    all
#    enabled:      true
>>>>>>> d4cf3b4b07f16988073e40fefe411c99f7d9ff93

