---

# BoM Processing variables
sapbits_location_base_path: "https://npceussaplib9f39.blob.core.windows.net/sapbits"
bom_base_name: "S4HANA_1809_SP5_v001"
target_media_location: "/usr/sap/install"

# SAP Configuration for templates and install
aas_hostname:
aas_instance_number:
app_sid: "X00"
download_basket_dir: "{{ target_media_location }}/download_basket"
hdb_hostname:
hdb_instance_number:
hdb_sid:
pas_hostname:
pas_instance_number:
password_hana_system:
password_master: "Passw0rd123"
sap_fqdn:
sapadm_uid: 2100
sapsys_gid: 2000
scs_hostname: "{{ ansible_hostname }}"
scs_instance_number: "00"
sidadm_uid: 2000
