---

- name: "Configure Disk mounted at {{ target_media_location }}"
  become_user: root
  become: yes
  block:
    - name: "Add {{ target_media_location }} partition"
      parted:
        state: present
        device: /dev/disk/azure/scsi1/lun0
        number: 1

    - name: "Create {{ target_media_location }}/ filesystem"
      filesystem:
        fstype: xfs
        dev: /dev/disk/azure/scsi1/lun0-part1

    - name: "Create {{ target_media_location }} mount point"
      file:
        path: "{{ target_media_location }}"
        state: directory

    - name: "Mount {{ target_media_location }}"
      mount:
        path: "{{ target_media_location }}"
        src: /dev/disk/azure/scsi1/lun0-part1
        fstype: xfs
        state: mounted
