---

- name: Configure Disk mounted at /usr/sap/install
  become_user: root
  become: yes
  block:
    - name: Ensure /usr/sap/install partition exists
      parted:
        state: present
        device: /dev/disk/azure/scsi1/lun0
        number: 1

    - name: Ensure /usr/sap/install filesystem exists
      filesystem:
        fstype: xfs
        dev: /dev/disk/azure/scsi1/lun0-part1

    - name: Ensure /usr/sap/install mount point exists
      file:
        path: /usr/sap/install
        state: directory

    - name: Ensure /usr/sap/install exists
      mount:
        path: /usr/sap/install
        src: /dev/disk/azure/scsi1/lun0-part1
        fstype: xfs
        state: mounted

    - name: Ensure /usr/sap/install subdirectories exist
      file:
        path: "/usr/sap/install/{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
      loop:
        - downloads
        - cd_exports
        - download_basket
