---

- name: "Ensure {{ base_bom }} is used"
  include_vars:
    file:       "{{ base_bom }}"
    name:       bom

- name: Group iterable tasks together
  vars:
    bom_dependencies: "{{ bom.materials.dependencies is defined | ternary(bom.materials.dependencies, []) }}"
    archive_location: "{{ bom.defaults.archive_location | regex_replace('/$', '') }}"
    target_location: "{{ bom.defaults.target_location | regex_replace('/$', '') }}"
  block:
    - name: Ensure media property is iterated
      vars:
        file_source: "{{ archive_location }}/{{ media_iterator.archive }}"
        file_dest_target_location: "{{ media_iterator.override_target_location is defined | ternary(media_iterator.override_target_location, target_location) | regex_replace('/$', '') }}"
        file_dest_target_name: "{{ media_iterator.override_target_filename is defined | ternary(media_iterator.override_target_filename, media_iterator.archive) }}"
        file_dest: "{{ file_dest_target_location }}/{{ file_dest_target_name }}"
        bom_media: '{{ bom.materials.media }}'
      # uri:
        # url: "{{ file_source }}"
        # dest: "{{ file_dest }}"
        # creates: "{{ file_dest }}"
        # src: "{{ file_source }}"
      debug:
        msg: "Download {{ file_source }} to {{ file_dest }}"
      loop: "{{ bom_media | flatten(levels=1) }}"
      loop_control:
        loop_var: media_iterator

- name: "Ensure {{ base_bom }} dependencies are followed"
  when: bom_dependencies | length != 0
  include_tasks: "./iterate_bom.yml"
  vars:
    bom_dependencies: "{{ bom.materials.dependencies is defined | ternary(bom.materials.dependencies, []) }}"
    bom_media: "{{ bom.materials.media }}"
    base_bom: "{{ bom_location_base_path }}/{{ item.name }}/bom.yml"
  loop: "{{ bom_dependencies | flatten(levels=1) }}"
