---

- name: "Ensure {{ bom_base_name }} is available"
  uri:
    url: "{{ sapbits_location_base_path }}/boms/{{ bom_base_name }}/bom.yml"
    dest: "/tmp/{{ bom_base_name }}_bom.yml"
    creates: "/tmp/{{ bom_base_name }}_bom.yml"
  delegate_to: localhost

- name: "Ensure {{ bom_base_name }} is used"
  include_vars:
    file: "/tmp/{{ bom_base_name }}_bom.yml"
    name: bom
  delegate_to: localhost

- name: "Ensure {{ target_media_location }} exists"
  file:
    path: "{{ target_media_location }}"
    state: directory

- name: "Ensure current property is iterated"
  vars:
    default_location: "{{ bom.defaults.target_location | regex_replace('/$', '') }}"
    bom_media: "{{ media_iterator.media }}"
    source_location: "{{ media_iterator.location }}"
    file_name: "{{ media_iterator.property_name }}"
  include_tasks: download_media.yml
  loop:
    - location: archives
      property_name: archive
      media: "{{ bom.materials.media | flatten(levels=1) }}"
    - location: templates
      property_name: file
      media: "{{ bom.materials.templates | flatten(levels=1) }}"
  loop_control:
    loop_var: media_iterator

- name: "Ensure {{ bom_base_name }} dependencies are followed"
  when: bom_dependencies | length != 0
  include_tasks: "{{ iterator }}"
  vars:
    bom_dependencies: "{{ bom.materials.dependencies is defined | ternary(bom.materials.dependencies, []) }}"
    bom_media: "{{ bom.materials.media }}"
    bom_base_name: "{{ item.name }}"
  loop: "{{ bom_dependencies | flatten(levels=1) }}"
