---

- name: "Ensure variables are available"
  include_vars:
    file: "../../../vars/sap-config.yml"

- import_tasks: pre_checks.yml

- include_tasks: "{{ iterator }}"
  vars:
    iterator: "./iterate_bom.yml"
