---
# Mount Filesystems
- name:     "Mount Filesystems"
  mount:
    src:    "{{ item.src }}"
    path:   "{{ item.path }}"
    fstype: "{{ item.type }}"
    opts:   defaults
    state:  mounted
  loop:
    # - { tier: 'all',          type: 'xfs',  src: '/dev/vg_sap/lv_usrsap',                                                       path: '/usr/sap' }
    - { tier: 'all',          type: 'xfs',  src: '/dev/vg_sap/lv_sap',                                                       path: '/usr/sap' }
    # - { tier: 'prepare',      type: 'xfs',  src: '/dev/vg_sap/lv_usrsapinstall',                                                path: '/usr/sap/install' }                # Special Install Structure; Destroy on Completion
    # - { tier: 'prepare',      type: 'xfs',  src: '/dev/vg_sap/lv_sapmnt',                                                       path: '/sapmnt' }
    # - { tier: 'hdb',          type: 'xfs',  src: '/dev/vg_sap/lv_hana_shared',                                                  path: '/hana/shared' }
    - { tier: 'hdb',          type: 'xfs',  src: '/dev/vg_sap/lv_shared',                                                  path: '/hana/shared' }
    # - { tier: 'hdb',          type: 'xfs',  src: '/dev/vg_hana_data/lv_hana_data',                                              path: '/hana/data' }
    - { tier: 'hdb',          type: 'xfs',  src: '/dev/vg_hana_data/lv_data',                                              path: '/hana/data' }
    # - { tier: 'hdb',          type: 'xfs',  src: '/dev/vg_hana_log/lv_hana_log',                                                path: '/hana/log' }
    - { tier: 'hdb',          type: 'xfs',  src: '/dev/vg_hana_log/lv_log',                                                path: '/hana/log' }
    # - { tier: 'hdb',          type: 'xfs',  src: '/dev/vg_hana_backup/lv_hana_backup',                                          path: '/hana/backup' }
    # - { tier: 'web',          type: 'xfs',  src: '/dev/vg_sap/lv_sapmnt',                                                       path: '/sapmnt' }
  when:         item.tier == "all" or
                item.tier == tier

...
