---

# -------------------------------------+---------------------------------------8
#
# Description:  Check the Main BOM for dependencies under materials
#                 (bom.materials.dependencies).
#               Download dependent BOM files.
#
# Example:      materials:
#                 dependencies:
#                   - name:      HANA_2_00_055_v1
#
- name:             Check for Microsoft Supplied BOM ({{ bom_name }})
  local_action:     stat path=BOM-catalog/{{ bom_name }}/{{ bom_name }}.yaml
  register:         microsoft_supplied_bom


- name:             Download BOM ({{ bom_name }}) from Storage Account
  get_url:
    url:            "{{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ bom_name }}/{{ bom_name }}.yaml{{ sapbits_sas_token }}"
    dest:           "{{ inventory_dir }}/{{ bom_name }}.yaml"
    mode:           0644
  register:         result
  until:            result is succeeded
  retries:          10
  delay:            6
  delegate_to:      localhost                                                     # Causes action to happen  on the Ansible Controller
  become:           no
  when:             microsoft_supplied_bom.stat.exists != true
# -------------------------------------+---------------------------------------8

...
