---

- name: Install OS packages
  package: 
    name: "{{ item }}" 
    state: present
  with_items: "{{ packages[ansible_os_family] }}"

- name: 2593824 - Additional Packages HANA 2 SPS04 
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libgcc_s1
    - libstdc++6
    - libatomic1
  when: hana_database.db_version is regex("2.\d{2}.0([4-9]\d|[0-9]\d{2,})") 

- name: Settings3.10 - Tweak the Default System Settings for SAP HANA 1 
  command: "saptune solution apply HANA"

- name: Settings3.10 - Tweak the Default System Settings for SAP HANA 2
  command: "saptune daemon start"
