---

# Install Jumpbox Components
- name: Create ostype varaible
  set_fact: 
     ostype: "{{ 'windows' if ansible_os_family == 'Windows' else 'linux' }}"

- name: Create dictionary with Linux Jumpbox information from output.JSON
  set_fact:
    jumpbox_comp_dict: "{{ jumpbox_comp_dict | combine({'linux': {'components': item.components}}) }}"
  loop: "{{ output.jumpboxes.linux|flatten(levels=1)  }}"
  when: item.name == 'jumpbox-linux' 

- name: Append Windows Jumpbox information to jumpbox_comp_dict
  set_fact:
    jumpbox_comp_dict: "{{ jumpbox_comp_dict | combine({'windows': {'components': item.components}}) }}"
  loop: "{{ output.jumpboxes.windows|flatten(levels=1)  }}"
  when: item.name == 'jumpbox-windows'

- name: Install Components on Jumpbox
  include_role:
    name: components-install
    tasks_from: "{{ component }}.yml"
  loop: "{{ jumpbox_comp_dict[ostype].components }}"
  loop_control:
    loop_var: component
