# /*----------------------------------------------------------------------------8
# |                                                                             |
# |                            Package Installation                             |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---
# --------------------------------------+---------------------------------------8
#
# Task: 2.1       - Package Installation for SAP
#
# TODO: split between OS and sap playbooks


- name:             2.1 - Import package list
  include_vars:     packages.yaml

- name:             "2.1 - Install OS packages: {{ ansible_os_family|upper }}-{{ ansible_distribution_major_version }}"
  package:
    name:           "{{ item }}" 
    state:          present
  loop:             "{{ packages[ansible_os_family|lower] }}"

# --------------------------------------+---------------------------------------8

# - name:       include OS-specific vars
#   include_vars:   "{{ ansible_os_family | lower }}.yaml"


# - name:       Ensure ({{ dependencies }}) exist
#   package:
#     name:         "{{ item }}"
#     state:        present
#   loop:           "{{ dependencies }}"

...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
