- name: remove vm and all resources except public ips
  azure_rm_virtualmachine:
     resource_group: "{{ az_resource_group }}"
     name: "{{ az_vm_name }}"
     state: absent
     remove_on_absent: all
