---

- name: Installing OS packages
  package: 
    name: "{{ item }}" 
    state: present
  with_items: "{{ packages[ansible_os_family] }}"

- name: Installing Hana 2.0 SPS04  packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
      - compat-sap-c++-7
      - libatomic
  when: "{{ output.databases|map(attribute='version')| join(',')}} == '2.00.043'"

- name: Enable and start tuned
  systemd:
     name: tuned
     state: started
     enabled: yes

- name:  Tuned profile
  command: "tuned-adm profile sap-hana"

- name: Disable SELinux
  selinux:
    state: disabled
  register: se_state

- name: SAP HANA NUMA configuration 
  copy:
    dest: /etc/sysctl.d/sap_hana.conf
    content: |
       kernel.numa_balancing=0

- name: Save sysctl.conf config
  command: sysctl -p /etc/sysctl.d/sap_hana.conf 

- name: Save sysctl.conf config
  command: sysctl -p /etc/sysctl.d/sap_hana.conf 

- name: Disable & numad service
  service:
     name: numad
     state: stopped
     enabled: no

- name: Create a symbolic link
  file:
    src: "{{ item.prop }}"
    dest: "{{ item.value }}"
    state: link
  with_items:
    - { prop: '/usr/lib64/libssl.so.10', value: '/usr/lib64/libssl.so.1.0.1' }
    - { prop: '/usr/lib64/libcrypto.so.10', value: '/usr/lib64/libcrypto.so.1.0.1' }

- name: Disable and stop abrt-ccpp
  systemd:
     name: abrt-ccpp
     state: stopped
     enabled: no

- name: Disable and stop abrtd
  systemd:
     name: abrtd
     state: stopped
     enabled: no

- name: Disable and stop kdump
  systemd:
     name: kdump.service
     state: stopped
     enabled: no

- name: Disable and stop firewall
  systemd:
     name: firewalld
     state: stopped
     enabled: no

- name: Reboot the machine if SELinux is disabled
  reboot:
  when: se_state.changed 
