---

- name: Installing OS packages
  package: 
    name: "{{ item }}" 
    state: present
  with_items: "{{ packages[ansible_os_family] }}"

- name: Installing Hana 2.0 SPS04  packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libgcc_s1
    - libstdc++6
    - libatomic1
  when: "{{ output.databases|map(attribute='version')| join(',')}} == '2.00.043'"

- name: Preconfigured SAP HANA settings
  command: "saptune solution apply HANA"
  when: ansible_os_family == "Suse"

- name:  enable tuned profile saptune
  command: "saptune daemon start"
  when: ansible_os_family == "Suse"
