---

# This is temperary solution to get bits from SMP

# Due to the file permission limitation with blob (always 770), we currently only support using azure files.
- name: Mount azure files
  include_tasks: "mount-azure-files/mount.yml"
  when: output.software.storage_account.account_kind == 'FileStorage'

- name: Install unzip
  apt: 
    name: unzip
    state: latest
    force_apt_get: yes
  delegate_to: localhost

- name: Download pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /usr/bin/get-pip.py
  delegate_to: localhost

- name: Install pip
  command: |
    python3 /usr/bin/get-pip.py
  delegate_to: localhost

- name: Install beautifulsoup4
  pip:
    name: beautifulsoup4
    state: latest
    executable: pip3
  delegate_to: localhost

- name: Create configuration json with SMP credentials
  template:
    src: hdb_json.j2 
    dest: "../python_scripts/downloader/hdb.json"
  delegate_to: localhost

- name: Download installation media
  shell: "python3 ../python_scripts/downloader/basket.py --config ../python_scripts/downloader/hdb.json --dir {{ azure_files_mount_path }}"
  delegate_to: localhost

- name: Identify media archive
  shell: "ls {{ azure_files_mount_path }}/DB|grep ZIP"
  register: bits_file
  delegate_to: localhost

- name: Extract media archive
  unarchive: 
    src: "{{ azure_files_mount_path }}/DB/{{bits_file.stdout}}"
    dest: "{{ azure_files_mount_path }}/DB"
    remote_src: yes
  delegate_to: localhost 
