---

- name: config common OS libs
  include_tasks: "dynamic/common_os_config.yml"

- name: config RedHat
  include_tasks: "dynamic/{{ ansible_os_family }}_os_config.yml"
  when:  ansible_os_family == "RedHat"

- name: config SUSE
  include_tasks: "dynamic/{{ ansible_os_family }}_os_config.yml"
  when:  ansible_os_family == "Suse"
