---

- name: Create dictionary with installation variant for Hana Database
  set_fact:
    hdb_variants: "{{ item.variants }}"
  loop: "{{ components }}"
  when: item.component == 'hana_database'

- name: Ensure the variant for LINUX is used
  set_fact:
    hdb_media_facts: "{{ item }}"
  loop: "{{ hdb_variants|flatten(levels=1) }}"
  when: item.os == 'LINUX'

- name: Check if a HANA database with the same SID has already been installed
  shell: "{{ hana_software_loc }}/{{ hdb_media_facts.media_loc }}/{{ hdb_media_facts.installer }} --list_systems | grep {{ hana_database.instance.sid }}"
  register: sid_existence_check_result
  failed_when: false
