---
- hosts: localhost
  roles:
     - { role: create-vm-cluster, vm_group: "hana_vm_group" }

- name: "roless"
  hosts: localhost
  tasks:
     - debug:
         msg: "Created HANA VM {{ item }}"
       with_items: "{{ groups['hana_vm_group'] }}"
