---
- hosts: localhost
  tasks:
    - include_vars:
        file: "{{ config_json_file }}"
        name: az_json
    - debug:
        msg: "config passed {{ az_json }}"

- hosts: localhost
  roles:
    - role: create-azure-vm
      vars:
        az_resource_group: "{{ az_json.az_resource_group }}"
        pip_name: "{{ az_json.az_vm_name }}-pip"
        public_ip_allocation_type: Dynamic
        domain_name: "{{az_json.az_vm_name}}"
        vm_size: Standard_D8s_v3
        vm_user: "{{ az_json.az_user }}"
        machine_name: '{{ az_json.az_vm_name }}'
        nic_name: "{{ az_json.az_vm_name}}-nic"
        subnet_name: "{{ az_json.az_subnet }}"
        nsg_name: "{{ az_json.nsg_id }}"
        vnet_name: "{{ az_json.az_vnet }}"
        vm_groups: bastion_linux_group
        ssh_public_key_file: "{{ az_json.az_public_key }}"
        ssh_private_key_file: "{{ az_json.ssh_private_key_file }}"
        other_host_vars:
            - config_json: "{{ az_json }}"
      when: az_json.linux_bastion == true

- hosts: bastion_linux_group
  tasks:
    - include_vars:
        file: "{{ config_json_file }}"
        name: az_json
    - debug:
            msg: "linux bastion host required: {{az_json.linux_bastion}}"

- name: install HANA Studio
  hosts: bastion_linux_group
  roles:
          - { role: setup-linux-hana-studio, when: az_json.linux_bastion == true,  azure_user: '{{ az_json.az_user }}', hana_studio_url: '{{ az_json.url_linux_hana_studio }}', sapcar_url: '{{ az_json.url_linux_sapcar }}' }
