---

- name: Packages3.2 - Installing OS package
  package:
    name: "{{ item }}" 
    state: present
  with_items: 
    - "{{ packages[ansible_os_family] }}"

- name: 2593824 - Additional Packages HANA 2 SPS04
  package:
    name: "{{ item }}"
    state: present
  with_items:
      - compat-sap-c++-7
      - libatomic
  when: hana_database.db_version is regex("2.\d{2}.0([4-9]\d|[0-9]\d{2,})")

- name: SELinux3.7 - Disable SELinux1
  selinux:
    state: disabled
  register: se_state

- name: SELinux3.7 - Disable SELinux2
  reboot:
  when: se_state.changed

- name: Disable3.8 - Disable Automatci NUMA Balancing1
  copy:
    dest: /etc/sysctl.d/sap_hana.conf
    content: |
       kernel.numa_balancing=0

- name: Disable3.8 - Disable Automatci NUMA Balancing2
  command: sysctl -p /etc/sysctl.d/sap_hana.conf 

- name: Disable3.8 - Disable Automatci NUMA Balancing3
  service:
     name: numad
     state: stopped
     enabled: no

- name: Links3.9 - Add Symbolic Links
  file:
    src: "{{ item.prop }}"
    dest: "{{ item.value }}"
    state: link
  with_items:
    - { prop: '/usr/lib64/libssl.so.10', value: '/usr/lib64/libssl.so.1.0.1' }
    - { prop: '/usr/lib64/libcrypto.so.10', value: '/usr/lib64/libcrypto.so.1.0.1' }


- name: UserProcesses3.13 - Maximum Number of Proccesses a User
  copy:
    dest: /etc/security/limits.d/99-sapsys.conf
    content: |
       '@sapsys soft nproc unlimited'
       '@sapsys hard nproc unlimited'

- name: Disable3.14 - Disable ABRT, Core Dumps and kdump 1
  systemd:
     name: abrt-ccpp
     state: stopped
     enabled: no

- name: Disable3.14 - Disable ABRT, Core Dumps and kdump 2
  systemd: 
     name: abrtd
     state: stopped
     enabled: no

- name: Disable3.14 - Disable ABRT, Core Dumps and kdump 3
  lineinfile:
    dest: /etc/security/limits.conf
    line: "{{ item }}"
  with_items:
    - '* soft core 0'
    - '* hard core 0'

- name: Disable3.14 - Disable ABRT, Core Dumps and kdump 4
  systemd:
     name: kdump.service
     state: stopped
     enabled: no

- name: Firewall3.15 - Firewall Configuration
  systemd:
     name: firewalld
     state: stopped
     enabled: no

- name: 2292690 - Tuned profile 1
  systemd:
     name: tuned
     state: started
     enabled: yes

- name: 2292690 - Tuned profile 2
  command: "tuned-adm profile sap-hana"
