#   SAP: Register BOM
#   SAP PAS: deploy PAS Parameter file install template
#   SAP PAS: Install

# TODO: Considerations
#         20G+ swap space
#         Livecache: None, HANA Internal, MaxDB External
#         message server acl
#         certificates
#         secure storage key
#

---
- name:  
  set_fact:
    sap_inifile:                  "{{ bom_base_name }}-pas-{{ ansible_hostname }}.params"
    sap_inifile_template:         "{{ bom_base_name }}-pas-inifile-param.j2"


# Returns bom object
- include_role:
    name:                         roles-sap/3.3.1-bom-utility
    tasks_from:                   bom-register
  vars:
    bom_name:                     "{{ bom_base_name }}"


- include_role:
    name:                         roles-sap/3.3.1-bom-utility
    tasks_from:                   bom-template
  vars:
    sap_cd_package_cd1:            
    sap_cd_package_cd2:           
    sap_cd_package_cd3:           
    sap_cd_package_cd4:           
    sap_cd_package_cd5:           
    sap_cd_package_hdbclient:     
    sap_ciInstanceNumber:         '00'
    app_instance_number:          
    sap_ciDialogWPNumber:         12
    sap_ciBtcWPNumber:            8
    sap_installSAPHostAgent:      "false"
    sap_profile_dir:              /usr/sap/{{ sap_sid|upper }}/SYS/profile
    sap_scs_hostname:             "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_SCS') | first }}"
    sap_db_hostname:              "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_DB')  | first }}"
    sap_ciVirtualHostname:        "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_PAS') | first }}"
    sap_appVirtualHostname:       


# *====================================4=======================================8
#   SAP PAS: Install
# 2230669 - System Provisioning Using a Parameter Input File
#
- name:               "SAP PAS Install"
  shell: |
                      set -o errexit
                      mkdir -p /etc/sap_deployment_automation
                      export TMPDIR=/usr/sap/install
                      ./sapinst SAPINST_INPUT_PARAMETERS_URL=/usr/sap/install/downloads/{{ sap_inifile }}     \
                                SAPINST_EXECUTE_PRODUCT_ID={{ bom.product_ids.pas }}                          \
                                SAPINST_SKIP_DIALOGS=true                                                     \
                                SAPINST_START_GUISERVER=false
                      touch /etc/sap_deployment_automation/sap_deployment_pas.txt
   args:
    chdir:            /usr/sap/install/SWPM
    creates:          /etc/sap_deployment_automation/sap_deployment_pas.txt
  # Skip when TRUE (test mode)
  # when: not test_new_bom
# *====================================4=======================================8

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
