---
# *====================================4=======================================8
#   SAP: BOM, Download
- name:           "Download BOM files"
  get_url:
    url:          "{{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ bom_base_name }}/{{ bom_base_name }}.yaml{{ sapbits_sas_token }}"
    dest:         "{{ target_media_location }}/{{ bom_base_name }}.yaml"
    mode:         0644
  register:       result
  until:          result is succeeded
  retries:        7
  delay:          5
# *====================================4=======================================8


# *====================================4=======================================8
#   SAP: Register BOM
- name:           "Register BOM"
  include_vars:
    file:         "{{ target_media_location }}/{{ bom_base_name }}.yaml"
    name:         sapbom

#------------------<DEBUGGING>-------------------
- debug:  
    msg:      "URL: {{ item.url }}"
  loop:       "{{ sapbom.BillOfMaterials|flatten(levels=1) }}"
#------------------</DEBUGGING>------------------
# *====================================4=======================================8

...