# /*---------------------------------------------------------------------------8
# |                           HANA utility commands                            |
# +------------------------------------4--------------------------------------*/

sapcontrol_command:                    "sapcontrol -nr {{ hdb_instance_number }}"
