---
disk_dict: {}
start: 0
azure_files_mount_path: "/sapmnt"
components_list: []
hana_install_path: "/hana/shared/install"
hana_software_loc: "{{ azure_files_mount_path }}/DB/DATA_UNITS"
components: "{{ lookup('file', '../components.json') }}"
hana_client_install_path: "/usr/sap/shared"
output: "{{ hostvars['localhost'].output }}"
sap_media_download_script: "/home/{{ansible_user}}/sap-hana/deploy/v2/ansible"
jumpbox_comp_dict: {}
