---
# Mount Filesystems
- name:     "Mount Filesystems"
  mount:
    src:    "{{ item.src }}"
    path:   "{{ item.path }}"
    fstype: "{{ item.type }}"
    opts:   defaults
    state:  mounted
  loop:
    # - { tier: 'pas',          type: 'nfs',  src: '{{ sap_sid|lower }}scs00.us.sap.contoso.com:/sapmnt/{{ sap_sid|upper }}',      path: '/sapmnt/{{ sap_sid|upper }}' }
    # - { tier: 'app',          type: 'nfs',  src: '{{ sap_sid|lower }}scs00.us.sap.contoso.com:/sapmnt/{{ sap_sid|upper }}',      path: '/sapmnt/{{ sap_sid|upper }}' }
    - { tier: 'hdb',          type: 'nfs4',  src: 'x01scs00lf02:/usr/sap/install',                 path: '/usr/sap/install' }                # Special Install Structure; Destroy on Completion
    - { tier: 'dbload',       type: 'nfs4',  src: 'x01scs00lf02:/usr/sap/install',                 path: '/usr/sap/install' }                # Special Install Structure; Destroy on Completion
    - { tier: 'app',          type: 'nfs4',  src: 'x01scs00lf02:/usr/sap/install',                 path: '/usr/sap/install' }                # Special Install Structure; Destroy on Completion
    - { tier: 'web',          type: 'nfs4',  src: 'x01scs00lf02:/usr/sap/install',                 path: '/usr/sap/install' }                # Special Install Structure; Destroy on Completion
  when:         item.tier == "all" or
                item.tier == tier

...
