# /*----------------------------------------------------------------------------8
# |                                                                            |
# |            Role for ensuring the swap space is configured correctly         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---
# -------------------------------------+---------------------------------------8
#
# Task: 1.1     - swap space setup
#
# -------------------------------------+---------------------------------------8

# TODO: 20210127 Review
#       1) This could be written to be more efficient
#       2) waagent config should not run on Baremetal
#          -Update: I have assumed that the tier for Baremetal is going to be named "HLI"

# - name:                           Ensure variables are available
#   include_vars:
#     file:                         "../../../vars/sap-disks.yaml"


- name:                           "Ensure /mnt/resource directory exists"
  file:
    path:                         "/mnt/resource"
    state:                        directory
    mode:                         "0755"
  notify:
    - "Ensure waagent is restarted"

- name:                           "validate /mnt/resource directory exists"
  stat:
    path:                         "/mnt/resource"
  register:                       swapfsdata

- name:                           "Ensure waagent file is configured with proper parameters"
  lineinfile:
    dest:                         /etc/waagent.conf  
    state:                        "{{ waagentconf.state }}"
    regexp:                       "{{ waagentconf.regexp }}"
    line:                         "{{ waagentconf.line }}"
  loop:
    - { state: 'present', regexp: 'ResourceDisk.Format=',     line: 'ResourceDisk.Format=y' }
    - { state: 'present', regexp: 'ResourceDisk.EnableSwap=', line: 'ResourceDisk.EnableSwap=y' }
    - { state: 'present', regexp: 'ResourceDisk.SwapSizeMB=', line: 'ResourceDisk.SwapSizeMB={{ item.swap_size_mb | default(2052) }}' }
  loop_control:
    loop_var:                     waagentconf
  when:                           swapfsdata.stat.exists and swapfsdata.stat.isdir
  register:                       swapfilemodified
  notify:
    - "Ensure waagent is restarted"


    # count_hana_data:        "{{ ((sap_swap|selectattr('tier', 'search', node_tier)|list|first).pvs|default('NOT_FOUND')).split(',')|count }}"
- debug:
    var:
      # count_hana_data:        "{{ ((sap_swap|selectattr('tier', 'search', node_tier)|list|first).swap_size_mb|default('2048')) }}"
      swap_size_mb:             sap_swap


...
