---

# Install HANA Client 

- name: Create dictionary with Hana Client information from Components
  set_fact:
    client: "{{ item }}"
  loop: "{{ components|flatten(levels=1) }}"
  when: item.component == 'hana_client'

- name: Install Hana Client
  shell: "{{ hana_software_loc }}/{{ item.media_loc }}/{{ item.installer }} -a client -b --hostname={{ ansible_hostname }} --path={{ hana_client_install_path }}"
  loop: "{{ client.variants|flatten(levels=1) }}"
  when: item.os == 'LINUX'
