---

- name: Create dictionary with installation variant for HANA Studio 
  set_fact:
    studio: "{{ item }}"
  loop: "{{ components }}"
  when: item.component == 'hana_studio'

- name: Copy to Hana Studio Installer
  win_copy: 
    src: "{{ hana_software_loc }}/{{ item.media_loc }}"
    dest: C:\Users\{{ ansible_user }}\install
  loop: "{{ studio.variants|flatten(levels=1) }}"
  when: item.os == 'WINDOWS'

# Install according to SAP Note 2098510 - Failed to load the JNI shared library error during HANA Studio Client Installation
- name: Install Visual C++ Redistributable Packages for Visual Studio 2013
  win_package:
    path: https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x64.exe
    product_id: vcredist
    arguments: /install /quiet

- name: Install Hana Studio on Windows jumpboxes
  win_shell: C:\Users\{{ ansible_user }}\install\{{ item.media_loc }}\{{ item.installer }} -a studio -b --path=C:\Users\{{ ansible_user }}\SAP_HANA_STUDIO
  args: 
    creates: C:\Users\{{ ansible_user }}\SAP_HANA_STUDIO
  loop: "{{ studio.variants|flatten(levels=1) }}"
  when: item.os == 'WINDOWS'
