---

- name: Create dictionary with installation variant for HANA Studio 
  set_fact:
    studio: "{{ item }}"
  loop: "{{ components }}"
  when: item.component == 'hana_studio'

- name: Copy to Hana Studio Installer
  win_copy: 
    src: "{{ hana_software_loc }}/{{ item.media_loc }}"
    dest: C:\Users\{{ ansible_user }}\install
  loop: "{{ studio.variants|flatten(levels=1) }}"
  when: item.os == 'WINDOWS'

- name: Install Hana Studio
  win_shell: C:\Users\{{ ansible_user }}\install\{{ item.media_loc }}\{{ item.installer }} -a studio -b --path=C:\Users\{{ ansible_user }}\SAP_HANA_STUDIO
  args: 
    creates: C:\Users\{{ ansible_user }}\SAP_HANA_CLIENT
  loop: "{{ studio.variants|flatten(levels=1) }}"
  when: item.os == 'WINDOWS'
