---

- name: Create device list
  shell: ls -l /dev/disk/azure/scsi1/* | awk '{split($0,disks," "); system("readlink -f " disks[9])}'
  register: device_list

- name: Create dictionary with disk name and devices list
  set_fact:
    start: "{{ start|int+item.count }}"
    disk_dict: "{{ disk_dict | combine({ item.name: {'count': item.count, 'devices': device_list.stdout_lines[start|int:start|int+item.count]} }) }}"
  loop: "{{ hdb_sizes[output.databases | map(attribute='size')| join(',')].storage }}"
  when: item.name != 'os'

- name: Create physical volume group
  lvg: 
    vg: "vg{{ item.key }}"
    pvs: "{{ item.value.devices | join (',') }}"
  with_dict: "{{ disk_dict }}"
  register: physical_vg
  failed_when:  physical_vg is failed

- name: Create logical volume group
  lvol:
    state: present
    vg: "vg{{ item.key }}"
    lv: "lv_hana_{{ item.key }}"
    size: 100%FREE
  with_dict: "{{ disk_dict }}"
  register: logical_vg
  failed_when: logical_vg is failed

- name: Create mount point directories
  file:
    path: "{% if item.key=='sap' %}/usr/{{ item.key }}{% else %}/hana/{{ item.key }}{% endif %}"
    state: directory
  with_dict: "{{ disk_dict }}"

- name: Creating filesystem on LVMs
  filesystem:
     fstype: "{{ output.databases|map(attribute='filesystem')| join('\n') | default('xfs') }}"
     dev: "/dev/vg{{ item.key }}/lv_hana_{{ item.key }}"
  with_dict: "{{ disk_dict }}"
  register: file_system
  failed_when: file_system is failed

- name: Add fstab entries and mount volumes
  mount:
    path: "{% if item.key=='sap' %}/usr/{{ item.key }}{% else %}/hana/{{ item.key }}{% endif %}"
    fstype: "{{ output.databases|map(attribute='filesystem')| join(',') | default('xfs') }}"
    opts: defaults
    src: "/dev/vg{{ item.key }}/lv_hana_{{ item.key }}"
    state: mounted
  with_dict: "{{ disk_dict }}"
  register: vol_mount
  failed_when: vol_mount is failed
