---
name:    'HANA_2_00_055_v0003ms'
target:  'HANA 2.0'
version: 3

materials:
#   templates:
    # - name:     X
    #   file:     HANA_2_00_055_v1.params
    #   override_target_location: "{{ target_media_location }}/config"

    # - name:     X
    #   file:     HANA_2_00_055_v1.params.xml
    #   override_target_location: "{{ target_media_location }}/config"

#   stackfiles:
    # # Download Basket permalinks
    # - name: Download Basket permalinks
    #   file: myDownloadBasketFiles.txt
    #   override_target_location: "{{ target_media_location }}/config"

  media:
    # SAPCAR 7.22
    - name:         SAPCAR
      archive:      SAPCAR_1010-70006178.EXE
      filename:     SAPCAR
      permissions:  '0755'
      url:          https://softwaredownloads.sap.com/file/0020000002208852020

    - name:         HANA Client
      archive:      IMDB_CLIENT20_007_26-80002082.SAR
      # extract:      true
      # extractDir:   CD_HDBCLIENT
      # creates:      SIGNATURE.SMF
      path:         download_basket
      url:          https://softwaredownloads.sap.com/file/0020000000381822021

    - name:         HANA Server
      archive:      IMDB_SERVER20_056_0-80002031.SAR
      extract:      true
      extractDir:   CD_HDBSERVER
      creates:      SIGNATURE.SMF
      url:          https://softwaredownloads.sap.com/file/0020000000958462021
      

    - name:         SAP HANA AFL Rev 54.1 only for HANA 2.0 Rev 54
      archive:      IMDB_AFL20_054_1-80001894.SAR
      extract:      true
      extractDir:   CD_HDBSERVER/COMPONENTS
      creates:      COMPONENTS/SAP_HANA_AFL/packages
      url:          https://softwaredownloads.sap.com/file/0020000000237172021

    - name:         LCAPPS for HANA 2.00.056.00 Build 101.01 PL 000
      archive:      IMDB_LCAPPS_2056_0-20010426.SAR
      extract:      true
      extractDir:   CD_HDBSERVER/COMPONENTS
      creates:      COMPONENTS/SAP_HANA_LCAPPS/packages
      url:          https://softwaredownloads.sap.com/file/0020000000958622021

    - name:         VCH AFL 1909 Rev 56.0 only for HANA 2.0 Rev 56
      archive:      VCH190900_2056_0-80004631.SAR
      extract:      true
      extractDir:   CD_HDBSERVER/COMPONENTS
      creates:      COMPONENTS/VCH_AFL_1909/packages
      url:          https://softwaredownloads.sap.com/file/0020000000958552021

    - name:         SAP HOST AGENT 7.21 SP51
      archive:      SAPHOSTAGENT51_51-20009394.SAR
      path:         download_basket
      url:          https://softwaredownloads.sap.com/file/0020000000363342021

    - name:         SAPHostAgent RPM Package
      archive:      saphostagentrpm_51-20009394.rpm
      url:          https://softwaredownloads.sap.com/file/0020000000269152021

...
