steps:
  - script: |
      set -e
      
      ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o ConnectTimeout=$(ssh_timeout_s) "$(username)"@"$(publicIP)" '
      source /etc/profile.d/deploy_server.sh

      # Modify environment value so it starts with u and with length of 5
      environment_env=${{parameters.environment_env}}
      buildId=$(Build.BuildId)
      isRelease=${environment_env%%$buildId*}

      if [ -z "${isRelease}" ]
      then 
        environment_prefix="U$(echo $(Build.BuildId) | rev | cut -c1-4 | rev)"
      else
        environment_prefix=${environment_env}
      fi

      environment_rg="${environment_prefix}-EAUS-SAP0-INFRASTRUCTURE"
      
      repo_dir=$HOME/${environment_rg}/sap-hana
      ws_dir=$HOME/Azure_SAP_Automated_Deployment/WORKSPACES/SAP_LANDSCAPE/${environment_rg}
      input=${ws_dir}/${environment_rg}.json

      echo "=== Checkout required branch ${{parameters.branch_name}} ==="
      cd $HOME/${environment_rg}/sap-hana && git checkout ${{parameters.branch_name}}
      
      echo "=== Enter workspace ${ws_dir} ==="
      cd ${ws_dir}

      terraform init -upgrade=true ${repo_dir}/deploy/terraform/run/sap_landscape/
      terraform plan -var-file=${input} ${repo_dir}/deploy/terraform/run/sap_landscape/ > plan_output.log
      cat plan_output.log
      
      if ! grep "No changes\|0 to change, 0 to destroy" plan_output.log; then exit 1; fi;
      '
    displayName: "Validate sap_landscape new config"
    env:
      ARM_CLIENT_ID: $(hana-pipeline-spn-id)
      ARM_CLIENT_SECRET: $(hana-pipeline-spn-pw)
      ARM_TENANT_ID: $(landscape-tenant)
      ARM_SUBSCRIPTION_ID: $(landscape-subscription)
