#   SAP: Register BOM
#   SAP DBLOAD: deploy DBLOAD Parameter file install template
#   SAP DBLOAD: Install

---
- name:             "Register BOM: {{ bom_base_name }}"
  include_vars:
    file:           "{{ inventory_dir }}/{{ bom_base_name }}.yaml"
    name:           bom

# *====================================4=======================================8

- name:  
  set_fact:
    sap_inifile:                  "{{ bom_base_name }}-dbload-inifile-param.j2"
    sap_virtual_hostname:         "{{ ansible_hostname }}"                         # SAP Install

# # -------------------------------------+---------------------------------------8
# #
# # Description:  Download specified BOM Template File
# #S41909SPS03_v1-scs-inifile-param.j2
# - name:             "Download BOM Template: {{ bom_base_name }}"
#   get_url:
#     url:            "{{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ bom_base_name }}/templates/{{ sap_inifile }}{{ sapbits_sas_token }}"
#     dest:           "{{ inventory_dir }}/{{ bom_base_name }}-scs-inifile-param.j2"
#     mode:           0644
#   register:         result
#   until:            result is succeeded
#   retries:          10
#   delay:            6
#   delegate_to:      localhost                                                     # Causes action to occur on the Ansible Controller
#   become:           no



# # *====================================4=======================================8
# #   SAP SCS: deploy SCS Parameter file install template
# - name:               "SAP SCS: deploy SCS Parameter file install template"
#   template:
#     src:              "{{ inventory_dir }}/{{ sap_inifile }}"
#     dest:             /usr/sap/install/downloads/{{ bom_base_name }}-{{ ansible_hostname }}.params
#     mode:             0644
#     force:            yes
# # *====================================4=======================================8


#------------------<DEBUGGING>-------------------
- name:       Parameters
  debug:  
    msg:
      - "Product              : {{ bom.product_ids.scs }}"
      - "SAP SID              : {{ sap_sid }}"
      - "Instance Number - SCS: {{ scs_instance_number }}"
      - "Virtual Hostname     : {{ sap_virtual_hostname }}"
      - "FQDN                 : {{ sap_fqdn }}"
      - "Master Password      : {{ password_master }}"
      - "sapadm UID           : {{ sapadm_uid }}"
      - "sapsys GID           : {{ sapsys_gid }}"
      - "<sid>adm UID         : {{ sidadm_uid }}"
#------------------</DEBUGGING>------------------


# # *====================================4=======================================8
# #   SAP DBLOAD: Install
# # 2230669 - System Provisioning Using a Parameter Input File
# #
# - name:               "SAP DBLOAD Install"
#   shell: |
#                       export TMPDIR=/usr/sap/install
#                       ./sapinst SAPINST_INPUT_PARAMETERS_URL=/usr/sap/install/downloads/{{ bom_base_name }}-{{ ansible_hostname }}.params \
#                                 SAPINST_EXECUTE_PRODUCT_ID={{ bom.product_ids.dbl }}                                                      \
#                                 SAPINST_SKIP_DIALOGS=true                                                                                 \
#                                 SAPINST_START_GUISERVER=false
#   args:
#     chdir:            /usr/sap/install/SWPM
#   # Skip when TRUE (test mode)
#   # when: not test_new_bom
# # *====================================4=======================================8


