#   SAP: Register BOM
#   SAP DBLOAD: deploy DBLOAD Parameter file install template
#   SAP DBLOAD: Install

---
- name:  
  set_fact:
    sap_cd_package_hdbclient:     
    sap_cd_package_cd1:           
    sap_cd_package_cd2:           
    sap_cd_package_cd3:           
    sap_cd_package_cd4:           
    sap_cd_package_cd5:           
    sap_profile_dir:              /sapmnt/{{ sap_sid|upper }}/profile
    sap_inifile:                  "{{ bom_base_name }}-dbload-{{ ansible_hostname }}.params"
    sap_inifile_template:         "{{ bom_base_name }}-dbload-inifile-param.j2"
    sap_scs_hostname:             "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_SCS') | first }}"     # SAP Install
    sap_db_hostname:              "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_DB')  | first }}"     # SAP Install



- include_role:
    name:                         roles-sap/3.3.1-bom-utility
    tasks_from:                   bom-register


- include_role:
    name:                         roles-sap/3.3.1-bom-utility
    tasks_from:                   bom-template


# *====================================4=======================================8
#   SAP DBLOAD: Install
# 2230669 - System Provisioning Using a Parameter Input File
#
- name:               "SAP DBLOAD Install"
  shell: |
                      export TMPDIR=/usr/sap/install
                      ./sapinst SAPINST_INPUT_PARAMETERS_URL=/usr/sap/install/downloads/{{ sap_inifile }}     \
                                SAPINST_EXECUTE_PRODUCT_ID={{ bom_base.product_ids.dbl }}                     \
                                SAPINST_SKIP_DIALOGS=true                                                     \
                                SAPINST_START_GUISERVER=false
  args:
    chdir:            /usr/sap/install/SWPM
  # Skip when TRUE (test mode)
  # when: not test_new_bom
# *====================================4=======================================8



...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
