
- name: "Get Deployer Keyvault name from keyvault"
  command: >-
    az keyvault secret show
      --vault-name {{ kv_uri }}
      --name  {{ deployer-kv-name }}
  changed_when: false
  register: deployer-kv-name
  no_log: false

- name: "Extract SAP Binaries Storage Account information"
  command: >-
    az keyvault secret show
      --vault-name {{ deployer-kv-name }}
      --name {{ sapbits-location-secret }}
  changed_when: false
  register: sapbits-location-base-path-secret
  no_log: false

  ansible.builtin.set_fact:
    sapbits-location-base-path: >-
      {{ (sapbits-location-base-path-secret.stdout | from_json).value }}
  no_log: false

- name: "Debug, storage account"
  ansible.builtin.debug: 
    var: sapbits-location-base-path
    

- name: "Extract SAP Binaries Storage Account SAS"
  command: >-
    az keyvault secret show
      --vault-name {{ deployer-kv-name }}
      --name {{ sapbits-sas-token-secret }}
  changed_when: false
  register: sapbits_sas_token-secret
  no_log: false

  ansible.builtin.set_fact:
    sapbits_sas_token: >-
      {{ (sapbits_sas_token-secret.stdout | from_json).value }}
  no_log: false

- name: "Debug, SAS Token"
  ansible.builtin.debug: 
    var: sapbits_sas_token
    

