---

- hosts: hanadbnodes
  become: true
  become_user: root
  vars:
    disk_dict: {}
    start: 0
    azure_files_mount_path: "/mnt/{{ hana_database.storage_acc }}"
    hana_install_path: "/hana/shared/install"
    hana_software_loc: "/mnt/{{ hana_database.storage_acc }}/DB/DATA_UNITS/HDB_SERVER_LINUX_X86_64"
  vars_files: 
     - "vars/packages.yml" 
  pre_tasks:
    - name: Include Hana DB sizes
      include_vars:
        file: ../hdb_sizes.json
        name: hdb_sizes

    - name: Include Output json
      include_vars:
        file: "/home/{{ ansible_user }}/output.json"
        name: output

    - name: Dictionary of Hana
      set_fact: 
        hana_database: "{{ item }}"
      loop: "{{ output.databases|flatten(levels=1) }}"
      when: item.platform == 'HANA'
  roles:
    - { role: OS_lib_install }
    - { role: OS_disks_preparation }
    - { role: Bits_download }
    - { role: Sap_hana_install }
