---

- hosts: hanadbnodes
  become: true
  become_user: root
  vars:
    disk_dict: {}
    start: 0
  vars_files: 
     - "vars/packages.yml" 
  pre_tasks:
    - name:
      include_vars:
        file: ../hdb_sizes.json
        name: hdb_sizes

    - name:
      include_vars:
        file: "/home/{{ ansible_user }}/output.json"
        name: output
  roles:
    - { role: OS_lib_install }
    - { role: OS_disks_preparation }
