---

- hosts: localhost
  become: true
  become_user: root
  pre_tasks:
    - name: Include output JSON
      include_vars:
        file: "/home/{{ ansible_user }}/output.json"
        name: output

    - name: Create dictionary with HANA database inforamtion from output.JSON
      set_fact:
        hana_database: "{{ item }}"
      loop: "{{ output.databases|flatten(levels=1) }}"
      when: item.platform == 'HANA'

# Prepare os, disks and mount points on Hana Database servers
- hosts: hanadbnodes
  become: true
  become_user: root
  vars_files: 
     - "vars/packages.yml" 
  pre_tasks:
    - name: Include SAP HANA DB sizes
      include_vars:
        file: ../hdb_sizes.json
        name: hdb_sizes
  roles:
#    - { role: os-preparation }
#    - { role: os-disk-setup }

# Mount Azure File share on all linux servers
- hosts: all_linux_servers
  become: true
  become_user: root
  roles:
#   - { role: mount-azure-files, when: output.software.storage_account_sapbits.file_share_name != "" }

# Download SAP Media on Azure File Share
- hosts: localhost
  connection: local
  become: true
  become_user: root
  pre_tasks:
    - name: Download pip
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /usr/bin/get-pip.py
  
    - name: Install winrm
      command:  "apt-get install python-winrm"

    - name: check winrm
      command: "python -c "import winrm"
      register: test
 
    - debug: var=test
    
    - name: connection debug
      command: "nc -z -w1 10.0.1.4 5986;echo $?"
      ignore_errors: true
      register: test_conn
      
    - debug: var=test_conn
  roles:
#   - { role: sap-media-download }

- hosts: jumpboxes_windows
  pre_tasks:
    - win_ping:
  roles:
    - { role: jumpbox-install }  
