---

# -------------------------------------+---------------------------------------8
#
# Description:  Download specified BOM Template File
#S41909SPS03_v1-scs-inifile-param.j2
#
# TODO: Download to the install directory
#       Fetch to controller
#       template to SWPM dir
#       adjust logic to handle BOMS same way 
#       use an ansible temp dir on controler
#
# - name:             "Download BOM Template: {{ bom_base_name }}"
#   get_url:
#     url:            "{{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ bom_base_name }}/templates/{{ sap_inifile }}{{ sapbits_sas_token }}"
#     dest:           "{{ inventory_dir }}/{{ bom_base_name }}-scs-inifile-param.j2"
#     mode:           0644
#   register:         result
#   until:            result is succeeded
#   retries:          10
#   delay:            6
#   delegate_to:      localhost                                                     # Causes action to occur on the Ansible Controller
#   become:           no


# Variables:
#       bom_base_name
#       sap_inifile_template
#       microsoft_supplied_bom_template
#       sap_inifile
#       sapbits_location_base_path
#       sapbits_bom_files
#       sapbits_sas_token
#       inventory_dir
#       bom_base.product_ids.scs
#       sap_sid
#       scs_instance_number
#       sap_scs_hostname
#       sap_fqdn
#       password_master
#       sapadm_uid
#       sapsys_gid
#       sidadm_uid




- name:             Check for Microsoft Supplied BOM ({{ bom_base_name }}) template
  local_action:     stat path=BOM-catalog/{{ bom_base_name }}/templates/{{ sap_inifile_template }}
  register:         microsoft_supplied_bom_template


# If Microsoft supplied BOM template found
- name:             "SAP SCS: deploy SCS Parameter file install template"
  template:
    src:            "{{ microsoft_supplied_bom_template.stat.path }}"
    dest:           /usr/sap/install/downloads/{{ sap_inifile }}
    mode:           0644
    force:          yes
  when:             microsoft_supplied_bom_template.stat.exists == true

# If Microsoft supplied BOM template not found
- name:             Retrieve BOM ({{ bom_base_name }}) template from Storage Account
  block:
    - name:             Download BOM ({{ bom_base_name }}) template from Storage Account
      get_url:
        url:            "{{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ bom_base_name }}/templates/{{ sap_inifile_template }}{{ sapbits_sas_token }}"
        dest:           "{{ inventory_dir }}/{{ sap_inifile_template }}"
        mode:           0644
      register:         result
      until:            result is succeeded
      retries:          10
      delay:            6
      delegate_to:      localhost                                               # Causes action to occur on the Ansible Controller
      become:           no

    - name:             "SAP SCS: deploy SCS Parameter file install template"
      template:
        src:            "{{ inventory_dir }}/{{ sap_inifile_template }}"
        dest:           /usr/sap/install/downloads/{{ sap_inifile }}
        mode:           0644
        force:          yes
  when:             microsoft_supplied_bom_template.stat.exists != true

#------------------<DEBUGGING>-------------------
- name:       Parameters
  debug:  
    msg:
      - "Product              : {{ bom_base.product_ids.scs }}"
      - "SAP SID              : {{ sap_sid }}"
      - "Instance Number - SCS: {{ scs_instance_number }}"
      - "SCS Virtual Hostname : {{ sap_scs_hostname }}"
      - "FQDN                 : {{ sap_fqdn }}"
      - "Master Password      : {{ password_master }}"
      - "sapadm UID           : {{ sapadm_uid }}"
      - "sapsys GID           : {{ sapsys_gid }}"
      - "<sid>adm UID         : {{ sidadm_uid }}"
#------------------</DEBUGGING>------------------
# -------------------------------------+---------------------------------------8





...
